### ISSUE TITLE
Text stroke not working

### ISSUE THREAD

**Issue by ykessler** [mogest/prawn-svg#101]
Text stroke does not render, whether applied as style or attribue:

```
<svg xmlns="http://www.w3.org/2000/svg" width="400" height="160">
  <text x="10" y="40"
      style="stroke: red;
             fill: blue;">
    SVG text styling
  </text>
 
  <text x="10" y="80" fill="blue" stroke="red" >
    SVG text styling
  </text>
</svg>
```
https://jsfiddle.net/msvcv93m/1/

 Is stroking text possible?

**Comment by mogest** [comment]
Hi @ykessler, thanks so much for the report.  I've implemented your suggestion.  If you wouldn't mind trying it out and confirming it works for you, that'd help!  And I'll release a new gem in the next week or two.

**Comment by ykessler** [comment]
@mogest kudos for the blazing response. It works great- thanks!
