### ISSUE TITLE
Non-standard prawn extension inclusion causing issues with prawn-rails update

### ISSUE THREAD

**Issue by CodingAnarchy** [mogest/prawn-svg#102]
I've been working on a PR to have prawn-rails automatically include all bundled Prawn extensions (see: cortiz/prawn-rails#29), but this is breaking with `prawn-svg`, because unlike most prawn extensions, which are accessed with a `require prawn/<extension_name>`, `prawn-svg` has its own workaround to work with `prawn-rails`.

Is there any way we can standardize on the `prawn/<extension_name>` format for the require so we can get this sorted out in `prawn-rails`?  This should eliminate the need for the Gemfile order workaround as well.

**Comment by mogest** [comment]
Hi @CodingAnarchy, sorry for the slow response.  I'm happy to do this; could you clarify what I should alter, or if it's easier to do than say submit a pull request?  Happy to do it myself but I can't quite work out what you're after from the description above.

**Comment by mogest** [comment]
Hey, just doing some housekeeping today.  It looks like from the referenced issue that you fixed it up in a different way, so I'll close this.  Let me know if there's anything I can do to help further.
