### ISSUE TITLE
Gradients are not shown properly if there are added multiple times

### ISSUE THREAD

**Issue by satirebird** [mogest/prawn-svg#104]
Linear gradients are shown correctly only on the first svg. If there is a second svg image the gradients are not shown or with some strange look. Asciidoctor-pdf also have problems with that. I created a simple test like this.

```ruby
require 'prawn'
require 'prawn-svg'

svg_data = IO.read("col_blue.svg")

Prawn::Document.generate("svgtest.pdf") do
  svg svg_data, width: 200
  text "Hello World!"
  svg svg_data, width: 100
end
```

The svg image is created with graphviz.

The result looks like this:
![gradient](https://user-images.githubusercontent.com/14821104/48837550-f6b09100-ed85-11e8-9bca-8b56695f5415.png)

The whole test can be found here:
[gradient.zip](https://github.com/mogest/prawn-svg/files/2603960/gradient.zip)

**Comment by mogest** [comment]
Hi @satirebird, thanks for the report.

Unfortunately I think this is a bug in the prawn gradients library (which I also helped write some of, but has been changed extensively since I implemented it.)  My guess is that the algorithm that tries to generate a unique key for each gradient is getting confused and thinking that the two different gradients are actually the same.

I don't have the time to work on the prawn codebase at the moment sorry, so probably your best bet is to head over there and raise the issue with them.

**Comment by satirebird** [comment]
Hello @mogest ,

it's not so easy. After getting the response from the prawn project I went deeper into the code. I checked the fill_gradient function and added some debug outputs. The bug has somthing to do with the transformation.
I tested the following code:
```ruby
  svg IO.read("col_blue.svg"), width: 50
  svg IO.read("col_blue.svg"), width: 50
  svg IO.read("col_blue.svg"), width: 50
```

The transformation variable in the function gradient_coordinates() contains the following parameters (one line for each svg):
```
[0.8064516129032258, 0.0, 0.0, 0.8064516129032258, 64.78104838709677, 752.5536290322581]
[0.6503642039542142, 0.0, 0.0, 0.6503642039542142, 59.210522892819974, 724.6046436004161]
[0.5244872612533985, 0.0, 0.0, 0.5244872612533985, 54.71816362324191, 702.0651392198986]
```
For each svg the gradient is **scaled** with the previously svg. This is wrong. I think it has something to do with the transformation_stack and / or with the save_graphics_state function. I am not the ruby expert. Can you help me please.

**Comment by mogest** [comment]
Nice debugging and good news!  It was a bug in prawn, albeit in code that I wrote... ah well.  Sorry about that.

You can refer to prawnpdf/prawn#1097 to keep track of the fix.  It's a one-line fix if you want to pop it in your own code.

**Comment by satirebird** [comment]
Cool, thank you very much. The fix works as expected. Now I can use SVGs with asciidoctor-pdf.
