### ISSUE TITLE
Use lowest opacity value when both opacity and fill-opacity properties are specified

### ISSUE THREAD

**Issue by mojavelinux** [mogest/prawn-svg#109]
When both opacity and fill-opacity are specified, most SVG programs seem to use the lowest opacity value of the two. prawn-svg always prefers the fill-opacity value.

Here's an example:

```
<svg xmlns="http://www.w3.org/2000/svg" width="206.404" height="167.984" viewBox="0 0 54.611 44.446">
<g transform="translate(-27.725 -80.097)" stroke="#000" stroke-width=".5">
<ellipse cx="48.451" cy="103.356" rx="20.476" ry="19.462" fill="#52e0ff"/>
<ellipse cx="66.77" cy="102.32" rx="15.316" ry="21.973" fill="#ff6c52" style="opacity:.75; fill-opacity:1"/>
</g>
</svg>
```

The second ellipse should be transparent. Every SVG viewer I tried displays it this way. prawn-svg is the exception.

I really don't know what's right here. But it probably makes sense for prawn-svg to align with what SVG viewers follow since that's what SVG creation tools make.

**Comment by mojavelinux** [comment]
Thanks @mogest!

**Comment by mogest** [comment]
Thanks for reporting as always :)

**Comment by mojavelinux** [comment]
Gladly! prawn-svg is really producing great results. Asciidoctor PDF users are going to love the update.
