### ISSUE TITLE
Enclosing anchor tag causes text to be dropped

### ISSUE THREAD

**Issue by mojavelinux** [mogest/prawn-svg#111]
If the text is surrounded in an anchor tag (as some diagramming tools like plantuml do), the enclosed text disappears. Here's an example:

```xml
<text fill="#000000" font-family="sans-serif" font-size="13" lengthAdjust="spacingAndGlyphs" textLength="78" x="14" y="196.6294">You can use</text>
<a target="_top" xlink:actuate="onRequest" xlink:href="http://plantuml.com/start" xlink:show="new" xlink:title="http://plantuml.com/start" xlink:type="simple">
<text fill="#0000FF" font-family="sans-serif" font-size="13" lengthAdjust="spacingAndGlyphs" text-decoration="underline" textLength="87" x="96" y="196.6294">links in notes</text>
<line style="stroke: #0000FF; stroke-width: 1.0;" x1="96" x2="183" y1="198.6294" y2="198.6294"/>
</a>
```

I'd like to discuss whether this is a case prawn-svg would be willing to handle, or whether I need to strip the enclosing `<a>` tag by manipulating the SVG data. I'm open to either option.

**Comment by mogest** [comment]
It's an SVG element so I'm happy to add support. It appears SVG doesn't
style links by default so it'll just be an element that does nothing except
render its children.

Will get it sorted this weekend.

**Comment by mojavelinux** [comment]
> It appears SVG doesn't style links by default so it'll just be an element that does nothing except render its children.

Agreed. It looks like plantuml is already applying manual styling to the text, so as long as prawn-svg just delegates to the children, it will appear correct (to the user).

**Comment by mogest** [comment]
Fixed in 388632f1bc743d61aece7704a776922f239f3984.  Also added support for textLength and lengthAdjust as in your sample code.

**Comment by mojavelinux** [comment]
Sweet! Thanks @mogest!

**Comment by mojavelinux** [comment]
@mogest Could you make a release when you get a chance? I'd like to include this improvement in the first stable release of Asciidoctor PDF.

**Comment by mogest** [comment]
Sure thing, done.

**Comment by mojavelinux** [comment]
Thanks!!
