### ISSUE TITLE
prawn-svg does not currently handle local references in < a > elements

### ISSUE THREAD

**Issue by stephenwhittle** [mogest/prawn-svg#115]
As per the discussion at https://github.com/asciidoctor/asciidoctor-pdf/issues/1521 , a local reference inside < a > tags in an svg is currently unhandled, but requires some special attention to be converted to a clickable link that will redirect to an anchor in the enclosing document. 
Here's a sample of such an input that links to an anchor called `_settingsmanager` : 

> < a href="#_settingsmanager" target="_top" title="#_settingsmanager" xlink:actuate="onRequest" xlink:href="#_settingsmanager" xlink:show="new" xlink:title="#_settingsmanager" xlink:type="simple">
> ...svg elements here...
> < /a >

Would it be possible to have support for this added?

**Comment by mojavelinux** [comment]
To be clear, it doesn't handle external references either. Currently, the `<a>` element acts like a `<g>`.

**Comment by mogest** [comment]
Hi @stephenwhittle.  I've had a look through the PDF spec to see how hard this would be, and 20 minutes in I'm thoroughly confused about how I'd go about implementing this.  It's not a prawn feature (as far as I can see) so I'd have to implement it directly into PDF, and at the moment I'd have no idea about how to go about doing that.

If you can point me to some source that shows how to make a link annotation that wraps the bounding box of an arbitrary set of PDF commands, and how to set a destination of a link annotation, I can implement it.

**Comment by mojavelinux** [comment]
I'm happy to share that this feature is supported by Prawn and rather simple to implement. You just define the `:anchor` option on the fragment to the name of the target. So if the source is `<a href="#target">go to target</a>`, then the assignment would be `fragment[:anchor] = 'target'`.

**Comment by mogest** [comment]
Oh, fantastic!  Thanks @mojavelinux.  I'll see what I can do.

**Comment by mojavelinux** [comment]
See https://github.com/prawnpdf/prawn/blob/master/lib/prawn/text/formatted/box.rb#L47-L52

**Comment by mogest** [comment]
Hmm the problem there is that only supports text.  An `<a>` can have anything inside it.

I'd have to get the bounds of the objects inside the `<a>` to get this working.  I started on that project when implementing gradients and many elements can report their (rectangular) bounding box.  But not text.  Given the huge number of text options there are, it's going to be quite tricky to calculate the bounding.  And again I don't think prawn can tell you the bounds of an arbitrary set of commands...

I suspect most of the time people will be using `<a>` with text, but I can't use formatted_text_box to do all the things that svg requires we do with text.

Seems like the only way forward here is to teach all elements how to report their bounding box, and live with the fact that the link annotation region will be rectangular and not conform exactly to the objects inside.  That's still quite a lot of work... hoping I've missed something!

**Comment by mojavelinux** [comment]
I agree, this is much more challenging on your end. I was only thinking about text. I suppose you could scope it to text and ignore it for other object types, at least to start. Tough call.

**Comment by mogest** [comment]
This is most likely going to stay out of scope for prawn-svg.
