### ISSUE TITLE
8-digit hex fills rendering as black

### ISSUE THREAD

**Issue by ajselvig** [mogest/prawn-svg#116]
Hello, not sure if this is an issue or just something that's not currently supported. 

I'm rendering a polygon with an 8-digit hex color (#357d9c33) as the fill. This renders correctly in the SVG file itself (in Chrome and Preview, I guess), but is completely black when I add it to a PDF using prawn-svg. 

I've attached the rendered PDF, as well as a screenshot of the actual SVG (Github apparently doesn't allow SVG attachments directly), and pasted the SVG markup below. 

Thanks for any guidance you can provide. 

```svg
<?xml version="1.0"?>
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="600px" height="600px" viewBox="0 0 600 600" version="1.1">
  <polygon points="586.6074655798081,360.37431797848836 402.31948677331303,366.24135499312905 401.49560735205847,385.896208537407 206.45421656164848,385.8978538283606 206.44958560964037,367.77858504833563 19.89225819242904,369.8290771464528 19.133275468101147,234.08191282340778 211.64531277832683,231.67213022315093 211.46426752823464,248.1846995120568 396.7894533363466,244.25856023618894 399.0867000928378,232.47080375486345 583.8896685579838,234.087222666501 586.6074655798081,360.37431797848836" fill="#357d9c33" stroke="#357d9c" stroke-width="4" stroke-linejoin="bevel" stroke-dasharray=""/>
  <polygon points="552.0,20.0 560,60.0 552.0,52.0 544.0,60.0" fill="#444444" style="transform: rotate(-44deg); transform-origin: 552.0px 74.0px"/>
  <text x="552.0" y="74.0" fill="#444444" text-anchor="middle" dominant-baseline="middle" font-size="20" font-weight="bold" font-family="sans-serif">N</text>
  <rect x="510.30799808044054" y="576" width="73.69200191955946" height="8" fill="#ffffff" stroke="#444444" stroke-width="2"/>
  <rect x="510.30799808044054" y="576" width="36.84600095977973" height="8" fill="#444444"/>
  <text x="584.0" y="572.0" fill="#444444" text-anchor="middle" font-size="16" font-family="sans-serif">0'</text>
  <text x="547.1539990402202" y="572.0" fill="#444444" text-anchor="middle" font-size="16" font-family="sans-serif">10'</text>
  <text x="510.30799808044054" y="572.0" fill="#444444" text-anchor="middle" font-size="16" font-family="sans-serif">20'</text>
</svg>
```

![Screenshot 2020-02-10 10 25 06](https://user-images.githubusercontent.com/455594/74168800-e3d6e600-4bef-11ea-8766-48fbd0af4fa5.png)

[fill-with-alpha.pdf](https://github.com/mogest/prawn-svg/files/4181901/fill-with-alpha.pdf)

**Comment by mogest** [comment]
Hi there,

8-digit hex colours don't appear to be valid SVG.  prawn-svg is a SVG 1.1 parser, and it's [definitely not in that spec](https://www.w3.org/TR/SVG11/types.html#DataTypeColor).  But I thought it'd be in the SVG 2 definition, but no, [its hex colours are only 3 or 6 digits long](https://www.w3.org/TR/css-color-3/#valuea-def-color) like SVG 1.1.

SVG 1.1 doesn't have `rgba()` for colours either, which would be the proper SVG 2 way of specifying a colour with alpha.

Is this SVG you've generated yourself?  I'd replace the colours with a 6-digit colour and use the `opacity`, `stroke-opacity` and `fill-opacity` properties to get what you're looking for.

**Comment by ajselvig** [comment]
Thanks for the quick and thorough response. It's interesting that it's not in the spec yet supported by multiple implementations, but I suppose that's not surprising. 

Yes, I'm generating these myself, so I'll just use fill-opacity. Thanks again for the help.
