### ISSUE TITLE
linearGradient does not support stop-opacity attribute

### ISSUE THREAD

**Issue by habamax** [mogest/prawn-svg#117]
I have created issue in asciidoctor-pdf https://github.com/asciidoctor/asciidoctor-pdf/issues/1561
But not sure if it is related to asciidoctor-pdf itself.

So there is a simple box with a linear gradient created in inkscape:

![image](https://user-images.githubusercontent.com/234774/74767371-cfea4e80-5297-11ea-808a-385a4770bcbf.png)

asciidoctor-pdf renders it

![image](https://user-images.githubusercontent.com/234774/74767440-e8f2ff80-5297-11ea-8092-7eb3c2c1ed76.png)

svg-file: [box-gradient.zip](https://github.com/mogest/prawn-svg/files/4221042/box-gradient.zip)

Thank you!

**Comment by mogest** [comment]
Hi @habamax.  Unfortunately prawn-svg doesn't support the `stop-opacity` attribute and there's no easy way to make it support it as prawn doesn't either.

There was another thing about your sample svg that prawn-svg didn't support (a gradient using an href to inherit from another gradient).  I've implemented that, but it doesn't help in your specific case I'm sorry :(

**Comment by habamax** [comment]
Hi @mogest , indeed, @mojavelinux explained it to me. 

Too bad inksape does simple gradients in unsupported way, but well, that is life :)

Thank you!

**Comment by mogest** [comment]
As of #175, stop-opacity is now implemented!
