### ISSUE TITLE
No support for <pattern> tag

### ISSUE THREAD

**Issue by oddhack** [mogest/prawn-svg#119]
As noted in https://github.com/asciidoctor/asciidoctor-pdf/issues/1621, asciidoctor-pdf forwards warnings about this WRT the 'test2.svg' image in the attached zipfile. N.b. I don't know how to make a minimal case using prawn / prawn-svg itself - the example on the README of this repo doesn't emit any warnings. But running the same image through asciidoctor-pdf
[test.zip](https://github.com/mogest/prawn-svg/files/4362726/test.zip)
 does 'forward' them and @mojavelinux assures me this is the right place to file a RFE.

**Comment by mojavelinux** [comment]
> the example on the README of this repo doesn't emit any warnings

That's because prawn-svg doesn't emit warnings. It returns them. So you need to print the warnings on the document object.

You can see how that is done here: https://github.com/asciidoctor/asciidoctor-pdf/blob/cc9428ff402b5ecebcfce86c039051b35759987e/lib/asciidoctor/pdf/converter.rb#L810-L826

**Comment by mogest** [comment]
Hi @oddhack, I've got no plans to implement <pattern> sorry.  This is documented in the README.
