### ISSUE TITLE
white-space: pre doesn't preserve sequences of white space

### ISSUE THREAD

**Issue by brandoncc** [mogest/prawn-svg#123]
I have this example:

```ruby
require 'prawn'
require 'prawn-svg'

Prawn::Document.generate("test.pdf") do
    svg '<svg id="svg-1588097344727" width="444" height="344"><style>.text-style {font-style:normal;font-size: 1em;white-space: pre;}.base-text-style {font-size: 26.0513px; font-family: \'Open Sans\';}</style><text x="0" y="0" class="base-text-style"><tspan x="0" dy="1em" class="text-style">This is a section of text which has</tspan>
    <tspan x="0" dy="1.5em" class="text-style"> </tspan>
    <tspan x="0" dy="1.5em" class="text-style"> </tspan>
    <tspan x="0" dy="1.5em" class="text-style">line</tspan>
    <tspan x="0" dy="1.5em" class="text-style"> </tspan>
    <tspan x="0" dy="1.5em" class="text-style">breaks</tspan>
    <tspan x="0" dy="1.5em" class="text-style">    and groups of spaces</tspan></text></svg>'
  end
```

I expect that there will be multiple spaces in a row as well as empty rows, but I get this instead:

![image](https://user-images.githubusercontent.com/543973/80523071-5c715700-8942-11ea-965e-19ddaf51da2b.png)

I would be fine with using `&nbsp;`, but that results in those six characters actually being printed in the PDF.

**Comment by brandoncc** [comment]
I just found `xml:space="preserve"` by reading the code base. That is deprecated, and `white-space: pre;` is recommended instead.

**Comment by mogest** [comment]
Hi @brandoncc, `white-space` isn't a [SVG 1.1 CSS property](https://www.w3.org/TR/SVG11/propidx.html), and prawn-svg is an SVG 1.1 parser.  Like you found, `xml:space` is the way it's done in SVG 1.1.

Not to say that we shouldn't implement this, but it'll go pretty low down the priority list.

**Comment by brandoncc** [comment]
That makes sense to me @mogest, thanks for the response. I render the SVG in a browser and then the same SVG in prawn, so I added both which covers my use case. I appreciate the explanation!
