### ISSUE TITLE
SVG with linked or embedded images are not rendered correctly

### ISSUE THREAD

**Issue by gern0** [mogest/prawn-svg#125]
Hi!
I'm using prawn-svg via asciidoctor-pdf and observed the following behaviour/issue:
Image elemets (either linked or embedded) in SVGs will not be rendered if the `defs` block is defined after elements refereing to it:

```
<svg ...>
    <g clip-path="url(#_clip1)">
        <g id="Crypt_35" transform="matrix(0.24,0,0,0.24,-297.6,-420.96)">
            <use xlink:href="#_Image2" x="0" y="0" width="2480px" height="3508px"/>
        </g>
    </g>

     ... other forms ...

    <defs>
        <image id="_Image2" width="2480px" height="3508px" xlink:href="data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEAY ... />
    </defs>
</svg>
```
I got such a SVG-structure via exporting with Affinity Publisher.
Applications such as eog, Inkscape and Gimp had no problems with a definition of the image object in the defs section after the reference in `<use xlink:href="#_Image2"`.

After manually putting the def-section before the reference everything got rendered correctly.

Example SVGs:
https://drive.google.com/drive/folders/1YfceF8wj2AtHzp8-O72xp7t3cHc7dJEf?usp=sharing

**Comment by mogest** [comment]
Hi @gern0, this was fixed a while ago but I haven't released a new gem since.  I'll do that shortly!  Sorry for that.

**Comment by mojavelinux** [comment]
Thanks @mogest! I just upgraded the main branch of Asciidoctor PDF to use it.

One thing I noticed is that the mimetype image/jpeg is not supported. It must be written as image/jpg. This could cause problems when using tools that are generating the image.

```
prawn-svg only supports base64-encoded image/png and image/jpeg data URLs
```

The regexp should probably be:

```
REGEXP = %r[\Adata:image/(png|jpe?g);base64(;[a-z0-9]+)*,]i
```

**Comment by mogest** [comment]
Hi @mojavelinux, I think you transposed the two MIME types in your message!

As far as I know there is no MIME type "image/jpg".  It's not in [the registry here](https://www.iana.org/assignments/media-types/media-types.xhtml#image).  Some people might use it by mistake but they shouldn't :)

**Comment by mojavelinux** [comment]
I meant it exactly as I wrote it. While image/jpg may not be an official MIME type, I've seen it used frequently enough to consider it a de-facto standard. If it's not supported, I'll certainly be fielding issues about it. And given how trivial the change is, that seems dumb.

**Comment by mogest** [comment]
Hmm.  You said image/jpeg isn't supported, it is supported.  You said it must be written as image/jpg, but it must be written as image/jpeg.

Sorry to hear you think it seems dumb!  I guess you thinking it's dumb doesn't convince me that it's the right thing to do though.  The SVG ethos doesn't subscribe to Postel's law.

**Comment by mojavelinux** [comment]
> Hmm. You said image/jpeg isn't supported, it is supported. You said it must be written as image/jpg, but it must be written as image/jpeg.

Aha! Yes, what I mean is that image/jpg isn't supported. That is a typo. But I think my example demonstrated what I was after.

I'll just have to hack it in Asciidoctor PDF then. I'm not going to waste time fielding issues about this.
