### ISSUE TITLE
prawn-svg not able to make https request to fetch svg image from url

### ISSUE THREAD

**Issue by cosmas28** [mogest/prawn-svg#129]
Hi, 
I'm using prawn-svg with `prawn` gem to render SVG images but it doesn't work with images served from url. I'm getting the following error and the documentation is not really clear with this kind of case.
![Screenshot 2020-10-27 at 09 15 46](https://user-images.githubusercontent.com/24792513/97264326-cb6a3280-1835-11eb-9aac-21d26578e877.png)

here is how I employed it on my PDF template
`svg IO.read('https://cdn.slangapp.com/assets/logo_lala.svg'), :enable_web_requests => true, :cache_images => true, :height => 37, position: :center`

Is there anything missing? @mogest

**Comment by mogest** [comment]
Hi, that's a problem with your IO.read not finding a file on disk, not
prawn-svg!

From memory there's something like
require 'open-uri'
that will allow you to read from web addresses like that, but it's not
recommended you use it. A bit dangerous security wise. Better that you use
Net::HTTP.get_response or a common Ruby web client like Faraday to do the
web request for you.

**Comment by clveranis** [comment]
Thanks for the heads up, how would you do this using `Net::HTTP.get?`

Using `svg URI.open(@user.drawing.service_url)` (which is the URL for the SVG file with Active Storage/S3), then it renders fine. 

However if I use something like `svg IO.read(Net::HTTP.get(URI.parse(@user.drawing.service_url)))` then I get a `File name too long @ rb_sysopen` error with the entire SVG data being read as the file name. 

Any thoughts?

**Comment by mogest** [comment]
Hi there.  This is more a general Ruby question than a prawn-svg question,
but you're trying to read a file that's named the contents of the GET
request.  `IO.read` is only for reading files.  Check out a Net::HTTP cheat
sheet to find out how to get the contents of a web resource, and pass that
string directly to `svg`.
