### ISSUE TITLE
Lines are shown in black in the svg generated by highcharts

### ISSUE THREAD

**Issue by fprambs** [mogest/prawn-svg#131]
When I export a chart from highcharts and render it, the series are displayed with a black color instead of the original color.

Original SVG
![g1](https://user-images.githubusercontent.com/7594127/100478411-e268a280-30c9-11eb-8743-effba845c22a.jpg)

Svg displayed
![g2](https://user-images.githubusercontent.com/7594127/100478421-ea284700-30c9-11eb-8421-f84aa598b86f.jpg)

Add my svg code in the link below

https://justpaste.it/8hvjb

Thanks !

**Comment by mogest** [comment]
Hi @fprambs, thanks for the report.  This SVG uses `rgba(r, g, b, a)` to specify its color, which is not supported by SVG 1.1 and therefore not by prawn-svg.  Highcharts should instead use `rgb(r, g, b)` for colors and the opacity property to get the subtle outline effect around their lines.
