### ISSUE TITLE
reference image in parent directory does not work

### ISSUE THREAD

**Issue by CWempe** [mogest/prawn-svg#138]
I want to create pdf files with `asciidoctor-pdf`.
My goal is to use a universal `theme` folder that can be copied into each project folder and links to a project specific title image.
The theme uses a `title_page_background.svg` wich is located in `./theme`.
In my project folder is a directory called `images` with a `title_image.jpg`.

```
projectA/
├── images/
|   ├── title_image.jpg
├── theme/
|   ├── title_page_background.svg
└──  my_document.adoc
```

So `title_page_background.svg` has a `xlink:href` pointing to `title_image.jpg` in `../images`.

```svg
<image
   xlink:href="../images/title_image.png"
</image>
```

This works in Inkscape.

But `title_image.jpg` does not get imported in the pdf with `asciidoctor-pdf` (and therefore `prawn-pdf`).
Adding `file://` did not help either.

It does work if `title_image.jpg` is in the same directory as the `title_page_background.svg`.

Sorry, if this is not a prawn-svg issue but an asciidoctor-pdf issue.

btw: can I see any logs from prawn-pdf on my WIndows machine using asciidoctor-pdf?
This could help with issues like this.

Thanks

**Comment by mojavelinux** [comment]
This is definitely not a prawn-svg issue. Unless you are absolutely certain that the issue with with prawn-svg itself, I strongly recommend not opening issues here that pertain to using Asciidoctor PDF.

**Comment by CWempe** [comment]
Sorry.
I guess this was due to the fact I did it the other way round in https://github.com/asciidoctor/asciidoctor-pdf/issues/1937.

I will post in the chat first, now.
