### ISSUE TITLE
Support CMYK colors

### ISSUE THREAD

**Issue by afdev82** [mogest/prawn-svg#140]
Hi all,

I have a feature request, I don't know how difficult it could be to support the following syntax for SVG v1.1 or v2: https://www.w3.org/TR/SVGColor12/#devicecmyk

I'm preparing PDF files to print and I have to enter all color values in CMYK.
It's already possible to do it in Prawn, but for svg images not.
I have svgs with RGB values that I can easily change to have the relative CMYK values too using the above syntax, but it seems that prawn-svg is not able to read them.

Also any workaround for this problem would be much appreciated.
I can spend also time to develop the requested feature by myself with some guidance if it makes sense, because I'm new to this project.
Thank you for your support!

PS: I thought a workaround could be to convert the final colors in Prawn, but I don't know if it's possible to get the result from prawn-svg and modify it.

**Comment by mogest** [comment]
Hi, thanks for the request. Do you have a simple sample SVG with CMYK that
we can use as a test?

**Comment by afdev82** [comment]
I have this one for example, I just used the syntax like in the docs:

```
<svg width="154" height="28" viewBox="0 0 154 28" xmlns="http://www.w3.org/2000/svg">
  <g fill="#000 device-cmyk(0.0, 0.0, 0.0, 1.0)" fill-rule="evenodd">
    <path d="m19.88 23.715-4.083 3.337a4.243 4.243 0 0 1-1.626-.965c-.463-.44-.768-.943-.915-1.508l-3.185 1.812c-.125.068-.336.138-.635.212a3.29 3.29 0 0 1-.754.11c-2.451 0-4.476-.841-6.073-2.524C1.011 22.506.212 20.168.212 17.175c0-2.846.83-5.192 2.491-7.039 1.66-1.847 3.777-2.77 6.353-2.77 1.027 0 1.988.203 2.88.61.892.407 1.479.768 1.762 1.084l2.948-1.067 1.034.305V19.92c0 1.016.178 1.824.533 2.422.354.599.91 1.057 1.667 1.373zm-7.166-2.541v-7.945a4.404 4.404 0 0 0-1.33-1.087c-.548-.303-1.217-.454-2.008-.454-1.141 0-2.086.416-2.837 1.248-.751.831-1.126 2.208-1.126 4.131 0 1.527.35 2.752 1.05 3.674.7.922 1.683 1.383 2.948 1.383.723 0 1.4-.113 2.033-.339.632-.227 1.055-.431 1.27-.611zM39.463 26.51h-3.947l-1.118-1.66-2.728 1.491c-.226.125-.553.217-.982.28a7.964 7.964 0 0 1-1.118.093c-2.666 0-4.69-.897-6.073-2.693s-2.081-4.049-2.092-6.759c-.011-2.937.822-5.274 2.499-7.014 1.677-1.739 3.894-2.609 6.649-2.609.79 0 1.485.062 2.083.187a5.903 5.903 0 0 1 1.728.661V.491h5.099V26.51zm-5.099-5.607v-8.03c-.283-.35-.751-.652-1.406-.906a5.855 5.855 0 0 0-2.134-.381c-1.423 0-2.482.415-3.177 1.245-.694.83-1.042 2.149-1.042 3.956 0 1.841.37 3.216 1.109 4.125.74.91 1.742 1.364 3.007 1.364.813 0 1.527-.135 2.143-.406.616-.271 1.116-.595 1.5-.967zM67.009 26.51h-5.184V15.075c0-.666-.237-1.256-.711-1.77-.475-.514-1.203-.771-2.186-.771-.938 0-1.722.195-2.354.584-.633.39-1.135.754-1.508 1.093V26.51h-5.184V8.299l5.184-.373v1.779l2.155-1.237a7.47 7.47 0 0 1 1.976-.805 8.464 8.464 0 0 1 2.01-.246c1.798 0 3.215.557 4.25 1.669 1.035 1.112 1.553 2.578 1.553 4.396V26.51h-.001zM89.303 17.057c0 2.993-.857 5.376-2.572 7.149-1.716 1.773-4.068 2.66-7.059 2.66-3.216 0-5.625-.892-7.227-2.677-1.603-1.784-2.404-4.162-2.404-7.132 0-2.699.863-5.008 2.59-6.929 1.726-1.92 4.073-2.88 7.041-2.88 2.979 0 5.328.887 7.05 2.66 1.72 1.774 2.581 4.156 2.581 7.149zm-5.252 0c0-1.479-.387-2.795-1.16-3.947-.773-1.152-1.844-1.728-3.21-1.728-1.57 0-2.694.525-3.372 1.575-.677 1.05-1.016 2.417-1.016 4.1 0 1.57.406 2.908 1.22 4.015.813 1.107 1.903 1.66 3.27 1.66 1.524 0 2.617-.449 3.278-1.347.66-.897.99-2.34.99-4.328zM101.145 23.325l-3.762 3.541c-1.559-.643-2.727-1.581-3.506-2.814-.779-1.233-1.17-2.708-1.17-4.42v-7.944H90.98V8.3h1.727V2.286l5.185-.373v6.404h2.71v3.354h-2.71v6.486c0 1.295.294 2.37.881 3.226.587.856 1.377 1.503 2.372 1.942zM121.981 23.715l-4.083 3.337a4.243 4.243 0 0 1-1.626-.965c-.464-.44-.769-.943-.915-1.508l-3.185 1.812c-.124.068-.337.138-.636.212a3.29 3.29 0 0 1-.754.11c-2.451 0-4.475-.841-6.072-2.524-1.599-1.683-2.398-4.021-2.398-7.014 0-2.846.83-5.192 2.491-7.039 1.66-1.847 3.777-2.77 6.353-2.77 1.027 0 1.988.203 2.88.61.892.407 1.479.768 1.762 1.084l2.948-1.067 1.033.305V19.92c0 1.016.178 1.824.533 2.422.355.598.913 1.057 1.669 1.373zm-7.166-2.541v-7.945a4.412 4.412 0 0 0-1.329-1.087c-.549-.303-1.218-.454-2.008-.454-1.141 0-2.087.416-2.838 1.248-.752.831-1.127 2.208-1.127 4.131 0 1.527.35 2.752 1.051 3.674.7.922 1.683 1.383 2.947 1.383.723 0 1.4-.113 2.033-.339.634-.227 1.057-.431 1.271-.611zM153.068 26.51h-5.15V15.075c0-.666-.229-1.256-.687-1.77-.457-.514-1.177-.771-2.159-.771-.803 0-1.52.155-2.152.466a4.972 4.972 0 0 0-1.592 1.211V26.51h-5.15V15.075c0-.666-.229-1.256-.686-1.77-.458-.514-1.178-.771-2.16-.771-.926 0-1.705.189-2.338.567-.633.378-1.096.749-1.389 1.11V26.51h-5.15V8.299l5.15-.373v1.779l2.016-1.237c.666-.406 1.32-.683 1.965-.83a8.86 8.86 0 0 1 1.965-.22c1.197 0 2.219.246 3.066.737a4.986 4.986 0 0 1 1.948 2.024l2.796-1.711a6.749 6.749 0 0 1 1.846-.788 8.17 8.17 0 0 1 2.084-.263c1.795 0 3.207.557 4.234 1.669 1.028 1.112 1.543 2.578 1.543 4.396V26.51zm0 0"/>
  </g>
</svg>
```

**Comment by mogest** [comment]
Pushed to master, let me know if you run into any problems with it.

I tried to find a reference to the idea that you could specify multiple space-delimited colours and couldn't find it anywhere.  The only time you can in SVG 1.1 is if you're passing in a URL and want a fallback colour if the URL doesn't work.  Also Chrome doesn't support it, so it doesn't appear to be out there in the wild.  I've left that part as is.

**Comment by afdev82** [comment]
Hi @mogest,
I continue to write here my issues.

If I have an SVG without a fill specified for some paths, the generated file has mixed color spaces.
In this case from what I could understand, the default color will be '000000' and it is specified in HEX (RGB) [here](https://github.com/mogest/prawn-svg/blob/master/lib/prawn/svg/color.rb#L5).
If I change the SVG and I explicitly set the fill to '#000' for each path, it's working fine.

Would it be possible to set a preference for the plugin like a "mode" (RGB vs CMYK) to decide in which format specify the default color? Something like a configuration option that could be set in an initializer.
I tried to change it to:
```
DEFAULT_COLOR = CMYK.new([0,0,0,100])
```
But it didn't work (I still get mixed colors), so maybe I'm wrong and the reason is not that.

[24147666.zip](https://github.com/mogest/prawn-svg/files/7224944/24147666.zip)
I attach an example of SVG with this issue.

Let me know if I can help in some way, thank you for your support.

**Comment by mogest** [comment]
Hi @afdev82.  I took a look at your SVG, both in Chrome and rendered using prawn-svg, and they look identical.  There are also no CMYK colours specified inside it?  I think I know what you're asking but not sure how that SVG relates to it?

**Comment by afdev82** [comment]
Yes, I sent you the original SVG with RGB colors.
If I changed the HEX codes with the corresponding CMYK colors, I would end up with a PDF containing a black RGB color.
I assume it's because this is the default color of the element without fill.
I attach the same SVG with the colors in CMYK.
[24147666_cmyk.zip](https://github.com/mogest/prawn-svg/files/7235759/24147666_cmyk.zip)

**Comment by afdev82** [comment]
I tried to use the `COLOR_MODE` to set the `DEFAULT_COLOR` in the `Prawn::SVG::Color` class, but it didn't work (because the constant in the class was read before the initializer).
I'm not sure it's a best practice, I tried with an `attr_accessor` too.
