### ISSUE TITLE
SVG Text Outline error in render

### ISSUE THREAD

**Issue by fprambs** [mogest/prawn-svg#141]
I'm trying to render a correctly generated svg from highcharts, but when rendering, the double text is smeared.
Attached image of original svg and rendered svg

Bad img
<a href="https://ibb.co/nc9d8p1"><img src="https://i.ibb.co/vPpyv9d/imagenmala.jpg" alt="imagenmala" border="0"></a>

Good img
<a href="https://ibb.co/qNtRjh2"><img src="https://i.ibb.co/1rD9QB4/imagenbuena.jpg" alt="imagenbuena" border="0"></a>

I also attach the svg file

https://justpaste.it/7vfs3

Can you help me please?

**Comment by mogest** [comment]
It doesn't look smeared to me?  It's a different font, though.

**Comment by mogest** [comment]
The SVG is very unusual
```
<text x="5" data-z-index="1" y="22" style="color:black;font-size:18px;font-weight:bold;fill:black;">
  <tspan class="highcharts-text-outline" fill="#FFFFFF" stroke="#FFFFFF" stroke-width="2px" stroke-linejoin="round" style="">
    43 500
    <tspan x="5" y="22">​</tspan>
  </tspan>
  43 500
</text>
```

I'm not sure why that last "43 500" isn't in the second tspan, or why the two tspans aren't siblings.

Don't think I can help you with this one sorry.  If you can come up with a small example that demonstrates a bug I'm happy to look into it further.

**Comment by fprambs** [comment]
> The SVG is very unusual
> 
> ```
> <text x="5" data-z-index="1" y="22" style="color:black;font-size:18px;font-weight:bold;fill:black;">
>   <tspan class="highcharts-text-outline" fill="#FFFFFF" stroke="#FFFFFF" stroke-width="2px" stroke-linejoin="round" style="">
>     43 500
>     <tspan x="5" y="22">​</tspan>
>   </tspan>
>   43 500
> </text>
> ```
> 
> I'm not sure why that last "43 500" isn't in the second tspan, or why the two tspans aren't siblings.
> 
> Don't think I can help you with this one sorry. If you can come up with a small example that demonstrates a bug I'm happy to look into it further.

**Comment by fprambs** [comment]
Estimated, indeed the bold family of the letter in question did not correspond to the normal family and was rendered badly. Thank you very much for the response and guidance. Greetings
