### ISSUE TITLE
Support for embedded SVG data URLs

### ISSUE THREAD

**Issue by alek3y** [mogest/prawn-svg#144]
It looks like images like this one are not supported (`...` is just to make the snippet shorter):
```svg
<image
  x="182.7" y="229.5"
  width="94.6" height="55"
  xlink:href="data:image/svg+xml;base64,PHN2ZyB4b...ZnPg=="
  preserveAspectRatio="none"
/>
```
I tried building a pdf with asciidoctor-pdf and the example in the readme, but both failed to show the embedded images.

**Comment by mojavelinux** [comment]
To my knowledge, prawn-svg only supports base64-encoded image/png and image/jpeg href values on the image tag.

**Comment by mogest** [comment]
Hi @alek3y, yes @mojavelinux is correct.  I'll update the README to be more specific about what image types prawn-svg supports.

**Comment by alek3y** [comment]
Wouldn't it be possible to also support image/svg? Some programs unfortunately embed the image as a url instead of putting its tags directly into the SVG.

**Comment by mogest** [comment]
Definitely possible but there'll be a bit of work required to get it going.
Happy to receive a pull request for this functionality.

**Comment by mogest** [comment]
Agreed mojavelinux, we'll track this in #137.
