### ISSUE TITLE
Embedded fonts

### ISSUE THREAD

**Issue by uidzip** [mogest/prawn-svg#145]
If I wanted to implement support for embedded fonts, where would I start in the code?  There's a lot of code dealing with fonts and its not immediately obvious to me where I would begin.

`<style>@font-face{font-family:"Arial Narrow";src:url(data:application/font-woff;charset=utf-8;base64,d09GRgABAAAAAC8AAA4AAAAAP5wAAl64AAAAAAAAAAAAAAAAAA...`

There's a python program here [convert woff to otf/ttf](https://github.com/hanikesn/woff2otf/blob/master/woff2otf.py) that can be ported to convert woff to ttf internally.

**Comment by mogest** [comment]
Hi there, happy new year. Prawn does all the heavy lifting when it comes to
fonts, the prawn-svg code you're seeing is more for css parsing and
selecting the right fonts based on their name. So I think your first step
would be just work directly with prawn and see if you can get it to
recognise a non-file-system based woff. If you get there, and register it
in the prawn font registry, prawn-svg should just work.

Good luck!

**Comment by mogest** [comment]
(let me know if you need help getting the font data out of the element)

**Comment by uidzip** [comment]
I don't intend to get prawn to work with woff.  I plan to convert the woff to ttf for prawn, its not a difficult conversion.  The trick is the woff is in the 'data:'.  The font data is embedded in the SVG, just like an embedded PNG or JPG.  So I have to extract the WOFF data from the SVG, convert it to TTF (I can handle that part fine), probably save it out to a temp file, and then get the temp file into the font registry, all before we start rendering any text.

Another trick to this is that the font can be embedded at the *end* of the SVG, after the text which uses it.  So I'm hoping prawn-svg is looking for data: elements before rendering anything.  I think it must since a PNG/JPG could also be embedded after it is used.

**Comment by mogest** [comment]
Got you. It would be a bit sad to have to write it out to a file, hopefully
you can find a way to inject directly in memory.

prawn-svg does do some file preprocessing, mainly for css I think, so we
could hook it in there. I'll take a look when I'm at my laptop in the next
few days and leave you my thoughts if you haven't already made progress.

**Comment by mogest** [comment]
Looking at the prawnpdf source, it appears that it can only accept files that are on the file system.

prawn-svg _could_ write the file to a temp directory and then get prawnpdf to read it, but I feel like at this stage it's better if anyone has this use case that they extract the font themselves before passing it to prawn-svg.

I would use regex to find a font-face declaration in the svg, slurp up the base64, and pop it in a file.
