### ISSUE TITLE
SVG to PDF encoding error

### ISSUE THREAD

**Issue by tsurezuregusa** [mogest/prawn-svg#146]
Greetings,

I am unsure if this is an issue with prawn itself or this gem. But prawn seems to be working fine, and there perhaps just missing something on the svg side. 

Trying to render a simple SVG as PDF with non-ASCII character gives an error:
`Prawn::Errors::IncompatibleStringEncoding: Your document includes text that's not compatible with the Windows-1252 character set. If you need full UTF-8 support, use external fonts instead of PDF's built-in fonts.`

This is the SVG string:

```
<?xml version="1.0" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">

<svg width="100%" height="100%" 
  xmlns="http://www.w3.org/2000/svg"
  xmlns:xlink="http://www.w3.org/1999/xlink">

<text x="100" y="100">
木
</text>

</svg>
```

And this is the script:

```
require 'victor'
require 'prawn-svg'
require 'prawn'

svgout = Victor::SVG.new

svgout.build { text "木", x: 100, y: 100 }

Prawn::Document.generate("svg.pdf") do
	font "#{ENV["HOME"]}/Library/Fonts/gkai00mp.ttf"
	text "山"
	svg svgout.render
end
```

Without `svg svgout.render.force_encoding('UTF-8')` the Chinese character renders correctly with no error.

**Comment by mogest** [comment]
Hi there, that error is a Prawn error.  You can load in your gkai00mp.ttf font into the Prawn font registry and then get your SVG to use it using `font-family` on a stylesheet, that may fix it.

**Comment by tsurezuregusa** [comment]
I did try `font-family`. Thank you for the reply.
