### ISSUE TITLE
vector-effect and not scaling stroke

### ISSUE THREAD

**Issue by afdev82** [mogest/prawn-svg#147]
Hi all,

I'm using prawn-svg to generate technical drawings with svg images representing parts.
I noticed that when I scale my svgs the stroke is scaled too and I would like to have the same stroke for all shapes in my pdf (I use other primitives of prawn to just draw other shapes).
I found that in theory I could add the ["vector-effect"](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/vector-effect) to each shape to specify to not scale the stroke. I think it's currently unsupported by prawn-svg. Even if it would be supported, I think it would be not so easy to change the existing and new svgs in the future.

Is there an alternative way to scale the svg but keep the stroke untouched?
In this way I could also have the possibilty to control the final stroke of the svgs just changing the line_width of the document.
At the moment I can't have the same stroke for all shapes, because their scale factor is different and the stroke is scaled with them.

Thank you for any help!

**Comment by afdev82** [comment]
I don't need this feature anymore, for my use case I've found another solution.
The scaling of the stroke is not a problem anymore.

**Comment by mogest** [comment]
Hi @afdev82, glad to hear you've found another solution.  `vector-effect` is an SVG 2.0 feature and out of scope for this SVG 1.1 parser.
