### ISSUE TITLE
The base64 dependency is too specific

### ISSUE THREAD

**Issue by BrianHawley** [mogest/prawn-svg#159]
You added `gem.add_runtime_dependency 'base64', '~> 0.1.0'` to the gemspec in version 0.34.0, but that is blocking base64 gem updates (or in my case, prawn-svg gem updates).

There is no reason to specify a version for your base64 dependency. If you insist on specifying a version, `'~> 0.1'` would be more than specific enough. 

For that matter, the base64 gem is really simple wrappers around methods built intop the String class. It would be easy to switch to calling that method directly, to remove the dependency.

**Comment by mojavelinux** [comment]
In fact, base64 is a [default gem](https://stdgems.org/), so there should be no reason to declare a dependency on it. It's already provided by the Ruby runtime and that should be the version preferred anyway.

> the base64 gem is really simple wrappers around methods built intop the String class.

Correct. The `Base64.decode64 str` call could be replaced by [String#unpack1](https://ruby-doc.org/3.2.2/String.html#method-i-unpack1):

```
str.unpack1 'm'
```

I ran the tests with this change and verified it does work.

**Comment by BrianHawley** [comment]
@mojavelinux the base64 gem is being promoted to a bundled gem in Ruby 3.4, so starting with Ruby 3.3, bundler shows a warning when you don't explicitly declare a dependency. Same for bigdecimal, and a few others. This is why a lot of other gems are now declaring base64 as a dependency, or removing the dependency using similar code tricks to what I did.

Just in case you're curious :)

**Comment by mojavelinux** [comment]
I've been using the base64 gem (in Asciidoctor) since Ruby 2.x and I have never seen such a warning (and no one has ever complained).

**Comment by BrianHawley** [comment]
The warning was added in Ruby 3.3. So, unless you had people looking ahead, any complaints would have happened since Ruby 3.3 came out on Dec 25, 2023.

**Comment by mojavelinux** [comment]
Got it.
