### ISSUE TITLE
SVG gradients with no name cause prawn-svg to explode

### ISSUE THREAD

**Issue by uidzip** [mogest/prawn-svg#162]
We have some customer-supplied SVGs that used to work, and now they don't.  Before when gradients were ignored, great.  Now, forms which used to render throw an error in gradients.rb, due to malformed gradient objects in the SVG which have no name and no definition.  PR on the way.  There might be a better way to do it, I just needed it to work quickly.

**Comment by mogest** [comment]
Fixed in #163
