### ISSUE TITLE
symbol without viewBox no longer renders properly when used

### ISSUE THREAD

**Issue by mojavelinux** [mogest/prawn-svg#164]
The fix for #157 caused symbol elements without a viewBox to no longer render properly when used by the use element.

I've attached an equation generated by a LaTeX to SVG library that no longer renders properly after the aforementioned fix.

![equation](https://github.com/mogest/prawn-svg/assets/79351/2128dc7b-63ad-463e-ac3b-924cb4a17a3f)

Here's how it looked before:

![equation-before](https://github.com/mogest/prawn-svg/assets/79351/09e7a19f-d6cc-4b2a-87b8-f1898609a8f5)

Here's how it looks after:

![equation-after](https://github.com/mogest/prawn-svg/assets/79351/267df270-2676-44e4-862b-e2f832f04d70)

A possible fix is to only apply the new logic if the viewBox attribute is present. It's also possible that this has something to do with the `overflow="visible"` attribute used in this SVG, which perhaps needs to be honored.

**Comment by mojavelinux** [comment]
Here's a simpler example with only a single symbol.

![symbol-m](https://github.com/mogest/prawn-svg/assets/79351/8e68c285-dbfd-455d-9496-f19e0b1b4be5)

**Comment by mojavelinux** [comment]
This problem doesn't seem to happen for all cases when a symbol is referenced by use. But it does seem to be happening when the contents of that symbol is a path. At least, as far as I can tell.

**Comment by mogest** [comment]
Thanks again @mojavelinux.  It turned out to be a rather fundamental problem with overflow handling.

I got the simple example you posted working, but the first example svg you posted is 404.  Would you be able to upload it again or give it a test with this fix? 🙏

**Comment by mojavelinux** [comment]
I can confirm that does the trick!

**Comment by mojavelinux** [comment]
Very strange that GitHub made the SVG private. I have no idea why it did that.

Here's a link to the equation SVG for reference: https://github.com/asciidoctor/asciidoctor-pdf/blob/v2.3.x/spec/fixtures/equation.svg

**Comment by mogest** [comment]
Neat, thanks!  I've released a 0.34.2 with the fix.

**Comment by mojavelinux** [comment]
Thanks!!
