### ISSUE TITLE
SVG Patterns are not rendered

### ISSUE THREAD

**Issue by ckucu** [mogest/prawn-svg#172]
Hello,

We are using prawn-svg via AsciiDoc and we are having issues with drawings using patterns.

I created a simple box with a pattern and attached here.
![boxWithPattern](https://github.com/user-attachments/assets/7a8077ea-394c-4d91-967c-ff49fb3fd966)

This SVG cannot be visualized properly while generating a PDF and we are having a warning:
asciidoctor: WARNING: problem encountered in image: /mdtApp/images/boxWithPattern.svg; Unknown tag 'pattern'; ignoring

We only see an empty box in the PDF.

Can you please help us with this issue?

Thanks in advance.

Best regards,

**Comment by mogest** [comment]
Hi @ckucu, unfortunately prawn-svg does not support patterns.  There are a few SVG 1.1 features listed at the bottom of the README which are not supported.
