### ISSUE TITLE
Not anymore compatible with prawn 0.12.0?

### ISSUE THREAD

**Issue by tmaier** [mogest/prawn-svg#43]
With the following gems

```
    prawn (0.12.0)
    prawn-qrcode (0.2.1)
      prawn (>= 0.11.1)
    prawn-svg (0.16.0)
      prawn (>= 0.8.4)
    prawn_rails (0.0.11)
      prawn (>= 0.11.1)
  prawn (~> 0.12.0)
  prawn-qrcode
  prawn-svg
  prawn_rails
```

and the following code in my pdf report

``` ruby
  def logo
    pdf.svg(logo_file, at: [25.mm, pdf.cursor], height: 25.mm)
  end

  def logo_file
    File.read(Rails.application.assets['logo.svg'].pathname)
  end
```

I get the pdf generated successfully, but the logo does not show up.

When I downgrade `prawn-svg` to 0.15.0.0, everything works as expected.

**Comment by mogest** [comment]
Hmm, I can't replicate that @tmaier.  Downgraded to prawn 0.12.0, popped the svg in the test suite and ran it against the latest prawn-svg, and it renders like this: http://seriousorange.com/psvg-sample.svg.pdf.

Happy to help out if you'd like to further diagnose the problem.
