### ISSUE TITLE
Issue with path: FloatDomainError: NaN

### ISSUE THREAD

**Issue by mikevm** [mogest/prawn-svg#50]
This problem seems similar to https://github.com/mogest/prawn-svg/issues/47 .  However I have upgraded my gem to 0.16.1 and the problem persists.

I have produced an SVG document using highcharts javascript library and prawn_pdf fails to render it.  I have cut the document down to the path that causes the failure.

```ruby
require 'prawn'
require 'prawn/fast-png'
require 'prawn-svg'

svg = <<-eosvg
<svg xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg" version="1.1" width="600" height="400">
<rect rx="0" ry="0" fill="#FFFFFF" x="0" y="0" width="600" height="400"/>
<g class="highcharts-series-group" zIndex="3">
    <g class="highcharts-series highcharts-tracker" visibility="visible" zIndex="0.1" transform="translate(0,10) scale(1 1)" style="cursor:pointer;">
        <path fill="#2f7ed8" d="M 294.98261140023453 102.62500177079593 A 85.375 85.375 0 0 1 294.98261140023453 102.62500177079593 L 295 188 A 0 0 0 0 0 295 188 Z" stroke-linejoin="round" transform="translate(0,0)"/>
    </g>
</g>
</svg>
eosvg

pdf = Prawn::Document.new
pdf.svg svg, at: [0, 0]
```

```
FloatDomainError: NaN
from /home/mikevm/.rvm/gems/ruby-2.1.1@vm/gems/prawn-svg-0.16.1/lib/prawn/svg/parser/path.rb:274:in `floor'
```

I can post my entire SVG document if necessary.

**Comment by mikevm** [comment]
i was able to make the problem "go away" with this:
```diff
--- a/lib/prawn/svg/parser/path.rb
+++ b/lib/prawn/svg/parser/path.rb
@@ -180,6 +180,8 @@ module Prawn
               y2 += y1
             end

+            return if (x1 == x2) && (y1 == y2)
+
             rx = rx.abs
             ry = ry.abs
             phi = (phi % 360) * 2 * Math::PI / 360.0
```

But I didn't know if this would eliminate some expected functionality, like using `A` to draw a complete circle.

**Comment by mogest** [comment]
Thanks for the report and for the solution.  The SVG spec helpfully says:

> If the endpoints (x1, y1) and (x2, y2) are identical, then this is equivalent to omitting the elliptical arc segment entirely.

So I think your fix is exactly on the money.
