### ISSUE TITLE
Not respecting xml:space="preserve" attribute on text nodes

### ISSUE THREAD

**Issue by raymondd222** [mogest/prawn-svg#51]
If you have an SVG with spacing in the text, and you need it to retain that spacing, Prawn SVG currently strips all the spacing in text nodes, whether or not this attribute is set.

**Comment by mogest** [comment]
Hi @raymondd222, thanks for raising the issue.  Would you be able to give me a block of SVG that correctly renders in a browser, but not with prawn-svg?

**Comment by raymondd222** [comment]
Any svg with whitespace in a text node, try this one:

<?xml version="1.0" encoding="utf-8"?><!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd"><svg version="1.1" width="422.859375" height="372.859375" viewBox="-25 0 422.859375 372.859375" xmlns="http://www.w3.org/2000/svg"  xml:space="preserve"><g transform='matrix(1.23055899339934 0 0 1.23055899339934 -121.39565284653466 -121.31882116336632)'><g>	<path d='M250,400.6C167,400.6,99.4,333,99.4,250S167,99.4,250,99.4S400.6,167,400.6,250S333,400.6,250,400.6z M250,116.8		c-73.4,0-133.2,59.8-133.2,133.2S176.6,383.2,250,383.2S383.2,323.4,383.2,250S323.4,116.8,250,116.8z' fill='#222222'/>	<path d='M250,134.2c-63.8,0-115.8,51.9-115.8,115.8S186.2,365.8,250,365.8S365.8,313.8,365.8,250S313.8,134.2,250,134.2z' fill='#222222'/></g></g><text font-size="121.05998621188118px" letter-spacing="0" font-family="Oswald-Regular" fill="#EEEEEE" x="55.4296875" y="241.98115439356437" xml:space="preserve">A    Z</text></svg>

Notice how 'A    Z' has space in it, and when it renders, it should have the A and Z be at opposite ends of the circle instead of next to each other

**Comment by mogest** [comment]
Sorry @raymondd222, if you want me to help fix the problem you're experiencing, you'll need to give me an SVG that replicates the problem otherwise I'll close this issue.

**Comment by raymondd222** [comment]
```
<?xml version="1.0" encoding="utf-8"?>
<!-- Generator: Adobe Illustrator 18.1.1, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 500 500" enable-background="new 0 0 500 500" xml:space="preserve">
<text xml:space="preserve" transform="matrix(1 0 0 1 103.5219 274.3552)" font-family="'PlayfairDisplaySC-Italic'" font-size="29.7376" letter-spacing="5">Text                (Far away text)</text>
	
</svg>
```

**Comment by mogest** [comment]
Thanks for your report, this will go into the next release.

**Comment by raymondd222** [comment]
Thanks, that's awesome!
