### ISSUE TITLE
SVG is not correctly rendered

### ISSUE THREAD

**Issue by gembin** [mogest/prawn-svg#54]
Please see issue here: https://github.com/asciidoctor/asciidoctor-pdf/issues/102

**Comment by mogest** [comment]
Hi there, @gembin.

Could you supply the SVG that is rendering incorrectly, please?

I can tell you straight away that some features that your image appears to use, such as arrow markers, are not supported by prawn-svg.  You are more than welcome to implement them, however!

I would imagine that the yellow boxes should work fine, though.  If you give me the SVG I can take a look as to why it's not rendering them.

**Comment by gembin** [comment]
@mogest, here is the [SVG file](https://gist.githubusercontent.com/gembin/627ab37327878d4d2d06/raw/f23842d0bcee21ef95625d5f7089b9b66b8311fc/gistfile1.svg).   

I'm not quite understand how prawn-svg works,  know nothing about ruby :-(.

**Comment by mogest** [comment]
Fixed in 2963544 and released gem 0.17.0.

Turns out it renders pretty well!  Just doesn't have the boxes' drop shadows.  Thanks for reporting it!

![screen shot 2015-04-29 at 10 45 21 pm](https://cloud.githubusercontent.com/assets/23133/7389383/72f989f0-eec1-11e4-8926-fe438bacfe1f.png)

**Comment by gembin** [comment]
That's great! thanks.

Is it possible to have the drop shadow working? and also the two vertical lines should be `dashed` instead of `solid`.

**Comment by mogest** [comment]
Unfortunately those are features not supported by prawn-svg at this time.  You might want to find a friendly ruby person and encourage them to implement them!

**Comment by mogest** [comment]
@gembin, I had a bit of free time in my weekend so implemented dashed paths and released a new prawn-svg gem.  Hope you enjoy.

**Comment by gembin** [comment]
Awesome!!!  Much appreciated for your great work!
