### ISSUE TITLE
Ignore shape with url() fill

### ISSUE THREAD

**Issue by mojavelinux** [mogest/prawn-svg#59]
Ignore the request to draw a shape (rect, circle, etc) if the fill value is a url() reference. This usually indicates an intent to fill a gradient, which Prawn SVG does not support.

As it is currently implemented, the shape gets filled with black (the default fill_color), which ruins many SVGs...in particular service badges.

**Comment by mogest** [comment]
I've taken a different approach to your issue, and implemented what the spec asks for (which happens to be what you were after too.)  Check my commit comments; I think that should solve the problem.

**Comment by mojavelinux** [comment]
That works great! Thanks for taking the time to develop the proper implementation.

I'm happy to say that shields / badges (like http://shields.io/) now rendering correctly. This is going to make a lot of people happy :)
