### ISSUE TITLE
Add a max_width option to constrain the maximum width of an image

### ISSUE THREAD

**Issue by mojavelinux** [mogest/prawn-svg#63]
Add a max_width option to constrain the maximum width of the image to a fixed size. This option is only used if the width (explicit or calculated) is greater than this value. This option makes it possible for an application to constrain the width of all images to a predetermined bounds (such as the width of the page) without needing to know the details of any given image.

Example:

```
svg IO.read('image.svg'), max_width: bounds.width
```

**Comment by mojavelinux** [comment]
Here's how I'm currently handling this in a post-processing step (to give you an idea of how it would work):

```ruby
svg_obj = ::Prawn::Svg::Interface.new (::IO.read image_path), self, position: position
if (svg_obj.document.sizing.output_width) > bounds.width
  svg_obj.document.sizing.requested_width = bounds.width
  svg_obj.document.sizing.calculate
end
```

However, it would be better if this could be handled internally.

**Comment by mogest** [comment]
I'm not super convinced about this one.  Is there a use case for having a max_width that's anything except <tt>bounds.width - x</tt>?  Don't want to add options just for the sake of adding options.

**Comment by mojavelinux** [comment]
I have a reasonable use case in mind. I'll follow up with the details shortly.

**Comment by mogest** [comment]
Hi @mojavelinux - do you want to proceed further with this one?

**Comment by mojavelinux** [comment]
I have to refresh my memory. I'll look into it this weekend. I trust my notes that says there's an important use case here :)

**Comment by mojavelinux** [comment]
I dug into the Asciidoctor PDF code and it seems like the code has moved on since filing this issue. The situation turned out to be more complicated.

I think it still would be nice to be able to have the requested width and height shrink to fit the bounds if they exceed it.

However, there's another issue that arises, which could actually cover this case. The SVG needs to be loaded in order to access the document's intrinsic sizing. Once that information is known, the application may want to adjust the values, such as to make the image fit the bounds or resize it to some percentage of the intrinsic dimensions. It would be nice if the SVG object had a "resize" method instead of having to initialize (and thus reparse) the SVG again.

You can see the relevant code in Asciidoctor PDF here: https://github.com/asciidoctor/asciidoctor-pdf/blob/75bc358438f4a8fbc6a2250f212366cf5c6528d4/lib/asciidoctor-pdf/converter.rb#L819-L829

To summarize, there's an interplay between the SVG's intrinsic size and the user scaling or constraining the image to the available bounds. In order to adjust the size, we first need to read the SVG. Then, there's usually a recalculation step. It would be helpful if the interface accommodated this workflow.

```ruby
svg_obj = ::Prawn::Svg::Interface.new svg_data, pdf_doc, position: position, width: width
rendered_w = (svg_size = svg_obj.document.sizing).output_width
if !width && rendered_w > bounds.width
  svg_obj.resize width: (rendered_w = bounds.width)
  svg_size = svg_obj.document.sizing
end
rendered_h = svg_size.output_height
```

The key line is:

```ruby
svg_obj.resize width: (rendered_w = bounds.width)
```

There's also the issue that the width and height (px) value in the SVG needs to be multiplied by 75% to convert it (roughly) to pt, but that's a separate issue.

**Comment by mogest** [comment]
How does that code look to you, @mojavelinux?

**Comment by mogest** [comment]
@mojavelinux, I might merge this in too for the next release if you're happy with it?

**Comment by mojavelinux** [comment]
Looks great to me!

**Comment by mogest** [comment]
Cheers.

**Comment by mojavelinux** [comment]
:beers:

**Comment by MilanCancarevic** [comment]
here is my solution for scaling image :
    ```
def set_image_dimensions(item)
      max = bounds.width
      width = item.metadata[:image_width] || max
      height = item.metadata[:image_height] || max

      # max width and height for image = bounds.width
      if width >= max || height >= max
        s = width >= height ? width : height
        { scale: max / s, position: :center }
      else
        { width: width, height: height, position: :center }
      end
    end
```
Here is for example if image is 2000x500 i want to make max width of image size of bounds.width
so i use scale and divine bounds.width with width/height, maybe this can be useful for someone
