### ISSUE TITLE
Is inline style tag supported?

### ISSUE THREAD

**Issue by art-solopov** [mogest/prawn-svg#64]
My SVG:

```svg
<svg xmlns="http://www.w3.org/2000/svg">
  <style>
    /* <![CDATA[ */
    rect {
    fill: white;
    stroke: black;
    }
    /* ]]> */
  </style>
  <rect x="0" y="0" width="200" height="100"></rect>
</svg>
```

My Ruby script:

```ruby
require 'prawn'
require 'prawn-svg'

Prawn::Document.generate('pr.pdf') do
  svg File.read('pic.svg')
end
```

The result:
![screenshot - 29 06 2015 - 19 28 40](https://cloud.githubusercontent.com/assets/5079987/8412817/1be448a4-1e95-11e5-9c9a-9065f77b280d.png)

P. S. Both Firefox and Inkscape display/convert the pic just fine.

**Comment by art-solopov** [comment]
Oops, sorry for not testing it properly.

**Comment by mogest** [comment]
Hi @art-solopov.  You shouldn't wrap your CDATA tags in /* */, is the real answer; SVG is by definition XML, and therefore any SVG parser must necessarily implement CDATA sections.

Given that browsers are pretty lenient, and I strive to render anything that browsers can, I've made prawn-svg handle the stray "*/" string.  Before the next gem is released you might just want to remove the comment though :)

**Comment by art-solopov** [comment]
@mogest I'll do just that, thank you! I was misguided by MDN. ^_^
