### ISSUE TITLE
undefined method `svg' for #<PrawnRails::Document:0xbcb05d08>

### ISSUE THREAD

**Issue by inyerade** [mogest/prawn-svg#67]
Hi 

I have problems with `svg` instruction. The following code give me `undefined method 'svg' for #<PrawnRails::Document:0xbcb05d08>`

But without `pdf.svg` works fine. Any idea?

file `Gemfile`
```
...
gem 'prawn-rails'
gem 'prawn-svg', '~> 0.21.0'
...
```

file `Gemfile.lock`
```
...
    prawn-rails (0.1.1)
      prawn
      prawn-table
      rails (>= 3.1.0)
    prawn-svg (0.21.0)
      css_parser (~> 1.3)
      prawn (>= 0.8.4, < 3)
    prawn-table (0.2.1)
...
```
file `show.pdf.prawn`
```
require 'prawn'
require 'prawn-svg'

prawn_document(:page_size =>  "LETTER" , :top_margin => 112.676 , :bottom_margin => 140.845 , :left_margin => 56.338 , :right_margin => 56.338 ) do |pdf|
    ...
    pdf.font_size(18) { pdf.text "<b>Médico</b>", :align => :center , :inline_format => true}
    pdf.move_down 8
    pdf.text " #{Rails.root} diagnósticos:", :inline_format => true;
    pdf.move_down 5
    pdf.svg (File.read("#{Rails.root}/app/assets/images/circle.svg")) , :at => [0, 600], :width => 500
end
```

**Comment by inyerade** [comment]
With this almost work but the pdf ceated is in Rails.root directory and do not apear in the browser.

```
require 'prawn'
require 'prawn-svg'
Prawn::Document.generate("colors.pdf") do |pdf|
    ...
    pdf.font_size(18) { pdf.text "<b>Médico</b>", :align => :center , :inline_format => true}
    pdf.move_down 8
    pdf.text " #{Rails.root} diagnósticos:", :inline_format => true;
    pdf.move_down 5
    pdf.svg (File.read("#{Rails.root}/app/assets/images/circle.svg")) , :at => [0, 600], :width => 500
end
```

Wich path I have to write to get the pdf in the browser or wich argument I have to write?

**Comment by mogest** [comment]
Hi @inyerade – these are questions that would be best answered by the prawn-rails community; it has nothing to do with prawn-svg.  Good luck!

**Comment by dvanoni** [comment]
I was able to solve this by adding the following line to `config/initializers/prawn_rails.rb`:

```ruby
PrawnRails::Document.extensions << Prawn::SVG::Extension
```

I am also using the Prawn Rails `prawn_document` method rather than Prawn's standard `Prawn::Document.generate`. This allows the PDF to be returned in the HTTP response rather than saved to the Rails.root directory.

@mogest does this seem like a valid solution?

**Comment by mogest** [comment]
Hi @dvanoni.  I'm surprised prawn-rails doesn't automatically import prawn's extensions; that might be a bug in prawn-rails?  I've never used it though, so I am probably missing something.  But yeah, if they don't automatically include prawn's extensions, then your solution sounds perfect.

**Comment by dvanoni** [comment]
Thanks for the response, @mogest.

It looks like __[PrawnRails::Document][]__ is a subclass of __Prawn::Document__, so I'm not sure why it doesn't have access to the extensions. I also may be missing something, but do you think it could have anything to do with the order in which the libraries get loaded?

My current solution seems to be working, so I don't want you to spend any time looking in to this—just thought I'd ask in case you had an idea off the top of your head.

Thanks!

[PrawnRails::Document]: https://github.com/cortiz/prawn-rails/blob/master/lib/prawn-rails/document.rb

**Comment by mogest** [comment]
I think you're right about load order.

Prawn has code that will copy the currently loaded extensions into a subclass:

```
irb(main):002:0> Prawn::Document.extensions
=> [Prawn::SVG::Extension]
irb(main):003:0> class Test < Prawn::Document
irb(main):004:1> end
=> nil
irb(main):005:0> Test.extensions
=> [Prawn::SVG::Extension]
```

But once the inherited class has been defined, it won't pick up any other extensions installed.

Is there any way we can force prawn-svg to run before prawn-rails?  How about the order they're included in the Gemfile?

**Comment by dvanoni** [comment]
@mogest you're right!

I moved `prawn-svg` before `prawn-rails` in the Gemfile and was able to remove the line from the initializer and have it all work.

Thanks for the suggestion! 👍

**Comment by mogest** [comment]
Thanks @dvanoni, I've added a note to the README for future prawn-rails users.
