### ISSUE TITLE
Add an example please

### ISSUE THREAD

**Issue by shevegen** [mogest/prawn-svg#69]
Hello.

The readme at:

    Prawn::Document.generate("svg.pdf") do
      svg svg_data, :at => [x, y], :width => w
    end

Does not work as-is because svg_data and w and x,y are not defined.

Could you provide a full example? I know a bit about prawn but nothing about prawn-svg; I failed to get this to work.

**Comment by ameuret** [comment]
```
require 'prawn'
require 'prawn-svg'

x = 100
y = 100
w = 300

svg_data = '<?xml version="1.0"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
  "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">

<svg xmlns="http://www.w3.org/2000/svg"
 width="467" height="462">
  <rect x="80" y="60" width="250" height="250" rx="20"
      style="fill:#ff0000; stroke:#000000;stroke-width:2px;" />
  
  <rect x="140" y="120" width="250" height="250" rx="40"
      style="fill:#0000ff; stroke:#000000; stroke-width:2px;
      fill-opacity:0.7;" />
</svg>'

Prawn::Document.generate("svg.pdf") do
  svg svg_data, at: [x, y], width: w
end
```
But as the README implies, the options have sane defaults that should show your svg rendering if omitted. If you do not see anything, check your coordinates and dimensions, and use `stroke_axis`.

**Comment by mogest** [comment]
Thanks for answering, @ameuret.
