### ISSUE TITLE
How can I place 2 svg file in one row?

### ISSUE THREAD

**Issue by yarving** [mogest/prawn-svg#70]
Why cann't I find any document of this prawn-svg?

**Comment by mogest** [comment]
Hi @yarving.  You place them as you place any other prawn element.  I think you just need to pass in `x` and `y` arguments to the svg call saying where you'd like the SVG placed.

Please use community Prawn support forums if you've got any further questions; github issues are for issues with the code.  Thanks.

**Comment by yarving** [comment]
@mogest Thanks, I record the `x` before inserting the first graph then give it as the parameter to the second can make that.

Thank you, I got the rule now.
