### ISSUE TITLE
Add support for file: schema for xlink:href attribute in image elements

### ISSUE THREAD

**Issue by AlexanderZobkov** [mogest/prawn-svg#71]
When preparing a SVG file in graphical editors (for example, Inkscape), embedded raster images usually presented by image elements that refers to actual image by using "file:" schema. For example: xlink:href="file:///<absolute path>" or xlink:href="file:<relative path>". Relative paths are resolved agains a path where the svg file is located.
Schemas like "http(s):" are not always can be used due to certain operation constrains. Schemas like "data:image" requires conversion (adding an additional burden/step for someone) of a image you want to embed into a SVG file.

**Comment by mogest** [comment]
Hi @AlexanderZobkov.  Are you willing to make a pull request for this change?

The only suggestion I'd make is that the file schema would have to be explicitly turned on using an argument to the svg call to prevent disclosure attacks, preferably by specifying a root path that files can be included from.

**Comment by AlexanderZobkov** [comment]
No, at the moment. I've came across to this feature when working on asciidoctor-pdf based documentation and trying to align a title page with my company requirements. Title page should include a couple of vector and bitmap elements. And I was surprised to found that I need to encode bitmaps into base64 and embed into a SVG file. If I'll not be able to embed bitmaps into the SVG file, probably I'll return to this issue.

**Comment by mogest** [comment]
I needed a bit of a break, and the UrlLoader code was in a bit of a bad shape, so did some refactoring and implemented your request.  It'll roll out in the next gem, and you can use it directly from the git repo until it does (master is generally pretty stable).

Let me know if you come across any issues.

**Comment by AlexanderZobkov** [comment]
Thanks for implementing the request! 

One comment, regarding 'enable_file_requests_with_root' option. IMHO, the name is confusing and can be renamed to 'file_schema_base_dir' since it's not a pure boolean option comparing to 'enable_web_requests' and 'cache_images' options.

Any schedule to release next version of the gem so that other projects would benifit from it?

My intention is to make this feature available toasciidoctor-pdf. As far as I know asciidoctor-pdf recently migrated to the latest available prawn-svg (0.22.1 - released, October 8, 2015)).

**Comment by mogest** [comment]
OK I'll have a think about the name.  Agree that it sounds unnecessarily boolean-y but I'm not a fan of 'file_scheme_base_dir' either.

I've just got a few big refactors going in too, just going to do a bit more work around them then will aim for a release sometime this week.

**Comment by mogest** [comment]
I decided to stick with the existing option name as I wasn't happy with any of the alternatives and like the consistency between options.

Also 0.23.0 is released, so it's all yours.  Thanks for suggesting this feature!
