### ISSUE TITLE
Parser crashes when color value is currentColor

### ISSUE THREAD

**Issue by mojavelinux** [mogest/prawn-svg#72]
The parser crashes if currentColor is used as a color value.

```
NoMethodError: undefined method `strip' for nil:NilClass
```

The currentColor keyword should resolve to the value of the computed color style of the current element. See https://developer.mozilla.org/en-US/docs/Web/CSS/color_value#currentColor_keyword for details.

At worse, the value should be ignored. However, since prawn-svg has access to the computed style of the current element, it seems reasonable to support the keyword.

Here's a modified example from the test suite (spec/sample_svg/tspan03.svg):

```xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
  "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg width="10cm" height="3cm" viewBox="0 0 1000 300"
     xmlns="http://www.w3.org/2000/svg" version="1.1">
  <desc>Example tspan03 - using tspan's x and y attributes
        for multiline text and precise glyph positioning</desc>
  <g font-family="Verdana" font-size="45" style="color: rgb(255,164,0)">
    <text style="fill: currentColor">
      <tspan x="300 350 400 450 500 550 600 650" y="100">
        Cute and
      </tspan>
      <tspan x="375 425 475 525 575" y="200">
         fuzzy
      </tspan>
    </text>
  </g>
  <!-- Show outline of canvas using 'rect' element -->
  <rect x="1" y="1" width="998" height="298"
        fill="none" stroke="blue" stroke-width="2" />
</svg>
```

The text should be yellow (i.e., `rgb(255,164,0)`).

**Comment by mogest** [comment]
Thanks for reporting this one.

I couldn't get it to crash; I'd love an example that made it crash if you've got one.

In any case, I implemented an inheritable color attribute, as previously `currentColor` would only work if there was a `color` attribute set on the same element.

**Comment by mojavelinux** [comment]
For the test case, see https://github.com/asciidoctor/asciidoctor-pdf/issues/407.

**Comment by mojavelinux** [comment]
:+1:

**Comment by mogest** [comment]
Hmm, it seems to work fine on 0.22.1, and in fact renders pretty much OK since the color attribute is specified on the same element as currentColor is used, in most cases.  Is asciidoctor using 0.22.1?

**Comment by mojavelinux** [comment]
Asciidoctor PDF is currently on 0.21.0. I'm kicking myself now for not checking the latest version. I'm excited to hear that it's already resolved. \o/ I'll upgrade Asciidoctor PDF asap.

**Comment by mojavelinux** [comment]
I can confirm that the upgrade resolves the issue. Thanks @mogest!
