### ISSUE TITLE
return nil from attributes 

### ISSUE THREAD

**Issue by tk0221** [mogest/prawn-svg#73]
https://github.com/mogest/prawn-svg/blob/master/lib/prawn/svg/document.rb#L38
I was getting `nil` attribute from Line 38, due to https://github.com/mogest/prawn-svg/blob/master/lib/prawn/svg/document.rb#L24 its not properly generate `@root`

My testing environment was really simple, I followed example code on README. It would be better if there is nil checker.

**Comment by mogest** [comment]
Thanks for the report @tk0221.  Can you give me an example of the code you used, please?  I don't have enough to go on here.

**Comment by tk0221** [comment]
![screen shot 2016-03-23 at 7 05 41 pm](https://cloud.githubusercontent.com/assets/5613513/14004816/157b5994-f12b-11e5-9977-0a5f2133231f.png)

Now I could able to create it, but that's what I got error message when I try to call `svg '~/my_local/picture.svg', :at => [0,0], :width => 100`

______________________________________
Can I ask something else?
1) Can I run this prawn-svg for multiple time inside of a pdf file? 
2) Do I must use under `Prawn::Document`? 
3) Can I call `svg` from other gem? (for example, I create another gem and call `svg` like https://github.com/tk0221/prawn-fillform/commit/a345f24bf93ca2a5a664c63f0d44a602b52d4afa) 

btw
Thanks for contribute open source and let me know any question.

**Comment by mogest** [comment]
Oh, right.  You can't pass a filename to `svg`, you have to pass SVG data.  I agree that the error message needs to be better.

As for your questions: 1) yes, 2) yes, 3) yes, as long as you've got prawn-svg as a dependency.

**Comment by tk0221** [comment]
Thanks for the answer :+1:

**Comment by mogest** [comment]
No problems, thanks for letting me know about the weird error.
