### ISSUE TITLE
prawn-svg-0.23.0/lib/prawn/svg/font.rb:23: warning: circular argument reference - font_registry

### ISSUE THREAD

**Issue by afdev82** [mogest/prawn-svg#74]
I got this warning while performing ```rake db:reset``` in rails.
Maybe adding ```self.``` to the default value could solve the issue.

**Comment by mogest** [comment]
Uh that was a dumb typo! :star2: 

Thanks heaps for reporting it.  I still couldn't get that warning message to appear, even on Ruby 2.3.  Gonna release a minor release in the next couple of days with a few fixes in it, so this will be in too.

Thanks again.

**Comment by AlexanderZobkov** [comment]
I've noticed the same warning while integrating prawn-svg-0.23.0 in asciidoctor-pdf. Will wait for the minor release to continue. Good to know that the working is already fixed!
