### ISSUE TITLE
Text disappears in svg image rendered in PDF.

### ISSUE THREAD

**Issue by wolandscat** [mogest/prawn-svg#77]
The SVG found [here](http://www.openehr.org/releases/AM/latest/docs/ADL2/diagrams/adl_text_overview.svg) renders in a PDF produced by asciidoctor-pdf (1.5.0.alpha.11), using prawn-svg 0.23.1 as coloured blocks, all positioning etc is fine, colours look correct, but just no text. This diag doesn't have colour gradients (at least I don't think it does), so I don't think that's the problem.

**Comment by mojavelinux** [comment]
The problem is that this SVG uses the `<foreignObject>` element, which in turn embeds HTML. As far as I know, the `<foreignObject>` element is only supported in a web browser (web browser supports a hybrid version of the SVG spec which is technically not compliant). Not even Inkscape can open this document (which is a clear sign that prawn-svg isn't going to be able to handle it either).

You'll need to "clean up" the SVG so that it only uses SVG elements.

**Comment by mojavelinux** [comment]
Interesting to note that `<foreignObject>` isn't supported by IE either.

**Comment by mojavelinux** [comment]
From the SVG 2 draft spec:

> Ultimately, it is expected that commercial Web browsers will support the ability for SVG to embed content from other XML grammars which use CSS or XSL to format their content, with the resulting CSS- or XSL-formatted content subject to SVG transformations and compositing. At this time, such a capability is not a requirement.

**Comment by wolandscat** [comment]
Ah.. I think what is happening here is that the SVG contains draw.io 'source' (some XML content that represents the diagram). This can be cleaned up in draw.io. I hadn't realised that this could affect rendering of SVGs - I haven't seen any fail on the web before due to this.

**Comment by mojavelinux** [comment]
>  I haven't seen any fail on the web before due to this.

Exactly, because what a web browser can render is very different from what a conforming viewer can render. There are really parallel SVG worlds, in this sense. (one of the contemporary complaints about SVG).

**Comment by wolandscat** [comment]
Right. So far, SVG has been a black box for me ...now I'm learning! Draw.io is pretty good, but its default of including the drawing 'source' in the export files is probably not that nice for various reasons - even just uselessly adding to page weight..... anyway, I'll test the fixed version and get back ASAP.

**Comment by mojavelinux** [comment]
:+1:

**Comment by mogest** [comment]
Thanks for your diagnoses, @mojavelinux. I think I'll implement `<switch>` so it ignores `<foreignObject>` blocks and renders the fallback content. At least the next person to run into this will (hopefully) have the fallback text to point them to what's happening.

**Comment by mojavelinux** [comment]
I agree that's definitely the right strategy. Thanks!

**Comment by mojavelinux** [comment]
Awesome!

**Comment by saurabhsingh-pvips** [comment]
I am facing this issue where texts are missing when svg is imported. 
Image in PDF.
![image](https://user-images.githubusercontent.com/57518239/70891181-bfee8e00-200c-11ea-929e-fc20e495c064.png)
vs 
Image in HTML.
![image](https://user-images.githubusercontent.com/57518239/70891219-d7c61200-200c-11ea-8dda-7a7a07ad02f0.png)

Asciidoctor version used:

```
Asciidoctor PDF 1.5.0.rc.1.dev using Asciidoctor 2.0.10 [https://asciidoctor.org]
Runtime Environment (ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)
```

**Comment by mogest** [comment]
Hi @saurabhsingh-pvips, I'll need the raw SVG so I can diagnose anything.

**Comment by saurabhsingh-pvips** [comment]
Here it is,
https://github.com/sifive/block-pio-sifive/blob/d125018d0b4f24ca5ceb1887b74121eccebf5076/docs/scribble/components/pio/pio-diagram.svg

**Comment by mogest** [comment]
Well... that is the most odd SVG I've ever seen, congratulations!

Having said that, it should work with prawn-svg.  I'll attempt to take a deeper look in the weekend, but it's got nothing to do with this particular issue you've attached it to.  Would you mind creating a new issue for this?  Thanks.

**Comment by saurabhsingh-pvips** [comment]
Alright. Will do. Thanks!
