### ISSUE TITLE
Add support for prawn document #image-method

### ISSUE THREAD

**Issue by RobWu** [mogest/prawn-svg#78]
Would be great if prawn-svg would be handle SVG for prawn "image"-method.

http://prawnpdf.org/api-docs/2.0/Prawn/ImageHandler.html

`Prawn.image_handler`

**Comment by mojavelinux** [comment]
Agreed. I've had to monkeypatch this into Asciidoctor PDF.

https://github.com/asciidoctor/asciidoctor-pdf/blob/master/lib/asciidoctor-pdf/prawn_ext/images.rb

**Comment by mogest** [comment]
This is a great idea, @RobWu, but I took a look at how image handlers are implemented, and the system expects a single PDF object back.  It's built only for single-file image embeds, not a rich document like SVG, which is a shame.

I could monkey patch the prawn image method but I don't feel super comfortable about that approach.

Until someone extends Prawn's image handler system, I'm going to have to pass on this one.

**Comment by mojavelinux** [comment]
I gather you're referring to the image handler extension point that prawn-gmagick taps into (see https://github.com/packetmonkey/prawn-gmagick/blob/master/lib/prawn/gmagick.rb).

I agree the extension point is too low-level. It should have delegated the entire inner implementation of the `image` method so the client can use a common interface, but the handler can completely take over control. As it stands now, the handler doesn't even have access to the options. I'm not sure why it was done this way.

Perhaps we should file an upstream issue?
