### ISSUE TITLE
CSS property from a more specific rule should take precedence

### ISSUE THREAD

**Issue by mojavelinux** [mogest/prawn-svg#79]
The CSS property from a more specific (i.e., stronger) rule should take precedence over the CSS property from a less specific (i.e., weaker) rule. This is not currently the case (at least in certain cases).

Consider the following example:

``` svg
<svg xmlns="http://www.w3.org/2000/svg" version="1.1" viewBox="0 0 100 100">
<style type="text/css">
.role { stroke: #555; fill: #ccc; }
text.role { fill: #000; stroke: none; }
</style>
<g>
<rect class="role" height="90" width="90" x="5" y="5"/>
<text x="50" y="50" class="role" text-anchor="middle">Square</text>
</g>
</svg>
```

``` ruby
require 'prawn'
require 'prawn-svg'

Prawn::Document.generate 'square.pdf' do
  svg ::IO.read('square.svg'), at: [0, cursor], width: 100
end
```

The text "Square" should appear in black (due to the fill property from text.role). Instead, the text appears in light gray, the same color that is used to fill the square. (You can discover the text is there by selecting it with a mouse). In this case, the fill property on `text.role` should take precedence over the fill property on `.role`.

**Comment by mojavelinux** [comment]
The workaround is to use a separate class name.

```svg
<svg xmlns="http://www.w3.org/2000/svg" version="1.1" viewBox="0 0 100 100">
<style type="text/css">
.role { stroke: #555; fill: #ccc; }
.role-text { fill: #000; stroke: none; }
</style>
<g>
<rect class="role" height="90" width="90" x="5" y="5"/>
<text x="50" y="50" class="role-text" text-anchor="middle">Square</text>
</g>
</svg>
```

**Comment by mogest** [comment]
Thanks @mojavelinux.  There are a few Ruby CSS parsers out there, but I can't find anything that applies CSS to a document, so I think I'm going to have to build that myself on top of css_parser.  It might be a while...

**Comment by mogest** [comment]
It's been a long time coming, but I finally found a relatively easy way of implementing this, woohoo!
