### ISSUE TITLE
Font selection is sticky

### ISSUE THREAD

**Issue by mojavelinux** [mogest/prawn-svg#80]
If the SVG uses a font (font-family, font-weight, or font-style), those settings getting applied to all subsequent text in the document (until the font is explicitly changed). The font selection should be local to the svg API call.

Here's an example that demonstrates the problem:

text.svg

```svg
<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="100" height="18">
<rect fill="#333" width="100" height="18"/>
<g text-anchor="middle" font-family="Courier" font-weight="bold" font-style="italic" font-size="12" fill="#fff"><text x="50" y="12">Sample Text</text></g>
</svg>
```

test.rb

```ruby
require 'prawn'
require 'prawn-svg'

Prawn::Document.generate 'output.pdf' do
  text 'before (in Helvetica font)'
  svg IO.read('text.svg'), at: [0, cursor]
  text 'after (in bold-italic Courier font)'
end
```

The after text should be in the same font as the before text. However, because the font selection in svg call is sticky, it takes on the font settings from the SVG instead.

**Comment by mojavelinux** [comment]
The workaround is to enclose the call to the `svg` method in `save_font`.

```ruby
save_font do
  svg IO.read('text.svg'), at: [0, cursor]
end
```

**Comment by mojavelinux** [comment]
To be clear, it's the last call to `select_font` that is sticky. Each time Prawn SVG draws text, it does a full font selection, so this doesn't impact font selection within the SVG drawable.

**Comment by mogest** [comment]
Thanks again @mojavelinux !
