### ISSUE TITLE
Ghostscript reports a warning when svg includes an image

### ISSUE THREAD

**Issue by AlexanderZobkov** [mogest/prawn-svg#81]
Ghostscript tool is used for various purposes, including validation of PDF files that they are not corrupted and can be read by a PDF viewer. 

The ghostscript tool reports the following warning when SVG  that was used to render into PDF included an image element.
```
$ gs -o null -sDEVICE=nullpage test.pdf
GPL Ghostscript 9.15 (2014-09-22)
Copyright (C) 2014 Artifex Software, Inc.  All rights reserved.
This software comes with NO WARRANTY: see the file PUBLIC for details.
Processing pages 1 through 1.
Page 1
   **** Warning: stream Length incorrect.
Loading NimbusSanL-Regu font from /usr/share/ghostscript/9.15/Resource/Font/NimbusSanL-Regu... 3771168 2299422 2564192 1236874 3 done.

   **** This file had errors that were repaired or ignored.
   **** The file was produced by:
   **** >>>> Prawn <<<<
   **** Please notify the author of the software that produced this
   **** file that it does not conform to Adobe's published PDF
   **** specification.
```
It's reproducable (reproducer is attached) on Ruby 2.2.1 and Jruby 9.0.5.0 (2.2.3) with the following set of gems:
```
[user@vm examples]$ bundle list
Gems included by the bundle:
  * Ascii85 (1.0.2)
  * addressable (2.4.0)
  * afm (0.2.2)
  * asciidoctor (1.5.4)
  * asciidoctor-pdf (1.5.0.alpha.13.dev)
  * bundler (1.12.5)
  * css_parser (1.4.5)
  * hashery (2.1.2)
  * pdf-core (0.6.1)
  * pdf-reader (1.4.0)
  * polyglot (0.3.5)
  * prawn (2.1.0)
  * prawn-icon (1.1.0)
  * prawn-svg (0.25.1)
  * prawn-table (0.2.2)
  * prawn-templates (0.0.3)
  * rake (10.5.0)
  * rouge (2.0.5)
  * ruby-rc4 (0.1.5)
  * safe_yaml (1.0.4)
  * thread_safe (0.3.5)
  * treetop (1.5.3)
  * ttfunk (1.4.0)
```

[test-jruby-9.0.5.0.pdf](https://github.com/mogest/prawn-svg/files/441062/test-jruby-9.0.5.0.pdf)
[test-jruby-9.0.5.0-with-no-image.pdf](https://github.com/mogest/prawn-svg/files/441063/test-jruby-9.0.5.0-with-no-image.pdf)
[test-ruby-2.2.1p85.pdf](https://github.com/mogest/prawn-svg/files/441061/test-ruby-2.2.1p85.pdf)
[test-ruby-2.2.1p85-with-no-image.pdf](https://github.com/mogest/prawn-svg/files/441060/test-ruby-2.2.1p85-with-no-image.pdf)
[reproducer.zip.txt](https://github.com/mogest/prawn-svg/files/441067/reproducer.zip.txt)

**Comment by mojavelinux** [comment]
This seems to be a problem with Ruby 2.2.x. If I use Ruby 2.3.x, then I get the correct stream length.

I tested both versions of Ruby using the same gems, which was a fresh install of prawn-svg 0.25.1 only.

**Comment by mojavelinux** [comment]
This problem is triggered when a raster image (jpg, png) embedded using the `<image>` tag is load.

The problem appears to be with the Prawn::SVG::Loaders::File. It uses `IO.read` to read the file of the embedded image instead of `IO.binread`. While Ruby 2.3 seems to figure out what to do, Ruby 2.2 does not. Whenever a binary file is read in, it needs to be done using binmode.

**Comment by mojavelinux** [comment]
If I change IO.read to IO.binread in the following file, it fixes the warning.

https://github.com/mogest/prawn-svg/blob/master/lib/prawn/svg/loaders/file.rb#L56

(Of course, we need to select the correct mode based on the type of file being read).

**Comment by mogest** [comment]
Thanks for the research, @mojavelinux!

**Comment by mojavelinux** [comment]
Sure thing!

The fix you added is consistent with the current implementation, which only supports image elements that reference a PNG or JPG file. Do you have plans to add support to the image element for SVG? If so, that's when we'd need to think about a switch to read the file as UTF-8.

**Comment by mogest** [comment]
No plans to implement svg <image> tags for now; no-one's requested it. I did leave a comment in the header of the class to remind me that it needs to be extended when we load text content though.
