### ISSUE TITLE
Exception thrown if SVG contains italic text

### ISSUE THREAD

**Issue by mojavelinux** [mogest/prawn-svg#82]
If the SVG includes text that has the font-style CSS property set to italic, Prawn SVG crashes. The crash occurs when Prawn attempts to invoke the `strip` method on a symbol.

Here's the problematic code in lib/prawn/svg/font.rb

```ruby
  def subfamily_name
    sfn = if weight == :normal && style
      style
    elsif weight || style
      "#{weight} #{style}"
    else
      "normal"
    end

    sfn.strip.gsub(/\s+/, "_").downcase.to_sym
  end
```

**Comment by mogest** [comment]
Just left a comment on your commit; can you review please?

**Comment by mojavelinux** [comment]
See reply in PR.

**Comment by mogest** [comment]
0.25.2 gem pushed.

**Comment by mojavelinux** [comment]
Thanks @mogest!
