### ISSUE TITLE
prawn-svg fails on svgs generated by Google Drawings

### ISSUE THREAD

**Issue by tkfu** [mogest/prawn-svg#84]
It's actually not all SVGs generated by Google Drawings, just ones that have images embedded. However, it's a very common use case for me: I make diagrams, and include an external icon or symbol or something. I'm attaching two nearly identical files: very-simple-google.svg is downloaded directly from google drawings, while very-simple-inkscape.svg is the same file, but opened in inkscape and saved as "Inkscape SVG". (note: I had to change the extension to .txt, as github doesn't allow you to attach svg files) The one directly from Google fails to render, throwing up these errors:

```
/Users/jon/.rvm/gems/ruby-2.2.3/gems/prawn-svg-0.25.2/lib/prawn/svg/elements/path.rb:52: warning: instance variable @last_point not initialized
/Users/jon/.rvm/gems/ruby-2.2.3/gems/prawn-svg-0.25.2/lib/prawn/svg/elements/path.rb:52: warning: instance variable @last_point not initialized
/Users/jon/.rvm/gems/ruby-2.2.3/gems/prawn-svg-0.25.2/lib/prawn/svg/elements/path.rb:52: warning: instance variable @last_point not initialized
/Users/jon/.rvm/gems/ruby-2.2.3/gems/prawn-svg-0.25.2/lib/prawn/svg/elements/path.rb:52: warning: instance variable @last_point not initialized
```
The one saved by Inkscape works.

[very-simple-google.svg.txt](https://github.com/mogest/prawn-svg/files/474561/very-simple-google.svg.txt)
[very-simple-inkscape.svg.txt](https://github.com/mogest/prawn-svg/files/474560/very-simple-inkscape.svg.txt)

**Comment by mogest** [comment]
Thanks @tkfu!  It was pretty simple in the end, Google uses scientific notation with a capital E, and I was only handling small 'e's.

The fix will go out with the next version, or you can target this commit in your Gemfile.

**Comment by tkfu** [comment]
Thanks for the ultra-quick fix, mogest—It's very much appreciated! Also, I feel like there has to be a merit badge or something for fixing a bug with a single keystroke.
