### ISSUE TITLE
Some SVG images aren't render correctly

### ISSUE THREAD

**Issue by Nowass** [mogest/prawn-svg#85]
Hi,

I use MS Visio for SVG images creation, but these images are not correctly rendered in generated PDF output. The problem is mainly with the multi-line text where all the lines are generated in one line. Other problems are the arrows at the end of the lines.

If the same (very similar) image is created for example in LilbreOffice Draw, the output is ok. I've tried a lot of other tools for SVG images (Google draw, Smart Draw, Inkscape, Pencil, ...) and so far it seems that the problem is only with the Visio images.

See attachment with PDF output example.

Do you have any idea what can be wrong?

Thank you,
Petr
[svgTest.pdf](https://github.com/mogest/prawn-svg/files/623870/svgTest.pdf)

**Comment by mogest** [comment]
Hi Petr, sorry to hear you're having troubles with prawn-svg.  Would you be able to attach an example SVG file that shows the problems you're experiencing please?

**Comment by Nowass** [comment]
Hi,
thanks for fast reply.

I've tried several svg outputs of one image exported from MS Visio, but none of them is working properly for me. Then the Visio drawing imported into LibreOffice Draw -> exported to SVG works (**_libreDraw.svg_**). See attachment.

P.S. the cleaned version is generated by the [SVG cleaner](https://github.com/RazrFalcon/svgcleaner-gui/releases)

[images.zip](https://github.com/mogest/prawn-svg/files/623993/images.zip)

Thanks,
**_Petr_**

**Comment by mogest** [comment]
Thanks Petr!  I've taken a look at the SVG output and found two bugs in prawn-svg:

1) This SVG specifies distance in `em` units, which prawn-svg doesn't support.
2) For some reason, prawn-svg is defaulting to `fill: black` instead of `fill: none` for some elements.  I've forgotten how this bit of the code works, but it should be a relatively easy fix.

I'll try to look into fixing these problems this weekend, but please excuse me if it's a bit longer.

**Comment by Nowass** [comment]
Perfect! Sounds good :o)

Many thanks for your fast support!

Have a nice day.
**_Petr_**

**Comment by mogest** [comment]
Turned out there were three problems, that has to be a record for a single SVG file!

I'd appreciate it if you could try it out by referencing prawn-svg directly from the github repo:

```
gem 'prawn-svg', git: "https://github.com/mogest/prawn-svg.git"
```

and let me know if you have any troubles with this one!  Thanks.

**Comment by Nowass** [comment]
Hi,
I've just quickly played with your update and so far so good. I'll check it more deeply within today and let you know :o)

Many thanks for your quick support!
**_Petr_**

**Comment by Nowass** [comment]
So I did more deep crosscheck on my other drawings, and I have to say that the multi-line problem is fixed and now it works perfectly.

but ... unfortunately, I found out other problems ...

in some of my drawings, the elliptical arc is not rendered correctly (see attached PDF). After several trials, I was able to find out the conditions which cause the problem. It always occurs , when the arc is scaled. If the original size is used, then it works well. So far it seems that the problem is only with this one shape, but frankly speaking, I did check only a few basic shapes and lines.

Do you have an idea what can be wrong?

[lines.zip](https://github.com/mogest/prawn-svg/files/630349/lines.zip)

I am not sure, if the next problem I am facing with, belongs to your module ... but anyway ...
The problem is the dotted line. Visio interprets this element as a sequence of lines with zero length. From my understanding, zero length should be represented as a single point. But in this case, I'll get an error that the zero length is not allowed. Up to now, I find out two ways how to handle this problem, but no one is really nice. The first option is to manually change the zero length to for example 0.01 and then it works ... but this means some image post processing every time it changed ... and this is not acceptable in the real project. The second one (the simplest) is to set a rule that dotted lines are forbidden ... then, for sure,  there is no problem :o) 

Do you have an idea how to deal with ?

**Comment by Nowass** [comment]
just a small update ... the second issue (zero length line) should belong to prawn module ... so it is not for you :o) 
**_Petr_**)

**Comment by mojavelinux** [comment]
@Nowass we could patch that in Asciidoctor PDF.

**Comment by Nowass** [comment]
@mojavelinux this would be great! 
I already put a comment here:

https://github.com/prawnpdf/prawn/commit/e65c24411c451918718a8e8cb35631c98ccc5517

so I hope I didn't create too many mismatches :-)

Thanks!
**_Petr_**

**Comment by mogest** [comment]
I've created a new issue for the scaled arcs not appearing correctly, #87, and will take a look when I can!  Thanks.
