### ISSUE TITLE
Scaled arcs do not appear correctly

### ISSUE THREAD

**Issue by mogest** [mogest/prawn-svg#87]
As reported by @Nowass in #85.

**Comment by Nowass** [comment]
Hi @mogest, since I reported this issue already a quite long time ago, I would like to ask when do you think this issue could be fixed? it's quite annoying to draw pictures where elements can't be scaled ...

**Comment by mogest** [comment]
I looked into it and it was difficult. Given this issue has sat here with no plus ones for almost a year, it's probably reasonably infrequently occurring.  If you're able to fix it and submit a PR, the community would appreciate your contribution.

**Comment by mogest** [comment]
Closing as this hasn't moved for a very long time.
