### ISSUE TITLE
Font size within teh SVG image is rendered wrongly, if the input size unit is *em*

### ISSUE THREAD

**Issue by Nowass** [mogest/prawn-svg#88]
Hi,
I've just figured out, that when the font size unit, within the SVG image, is em, then the font size in output PDF is wrong.

Attached are two SVG pictures ... the same picture once with the font size 0.75em and then with font size 9pt. These values should be equal (based on this [converter](http://www.convertunits.com/from/pt/to/em)), but the output PDF is rendered differently.
The output with the pt units is perfectly 1:1 with the what I see in MS Visio

The generated PDF is also part of the zip file ...

[doc.zip](https://github.com/mogest/prawn-svg/files/661330/doc.zip)

Thanks for support,
**_Nowass_**

**Comment by mogest** [comment]
Hi.  Looking at these two SVGs as rendered by Chrome, they have two different sizes, the same as prawn-svg displays!

Looking at the source, I can see why they should all be displaying in 9pt.  The fact that Chrome isn't doing that is pretty suspicious.  Could you do some more digging for me please?  I aim to render like Chrome, unless where I can prove Chrome doesn't meet the SVG spec correctly.

**Comment by Nowass** [comment]
Hi,
thanks for your feedback ... I did another crosscheck, and frankly speaking in my case, the PDF output is different than the Chrome one.

In my case, the only "correct" (or at least the same as from Inkscape, which I use as a reference) output I get with **pt** units. From this trial it seems that the font with size **1em = 12pt = 100%** is generated correctly in most cases (only px unit fails).

This leads to the question ... Could the problem be somewhere else during PDF generation than in the prawn-svg module?

[svgFontSize.zip](https://github.com/mogest/prawn-svg/files/665826/svgFontSize.zip)

Thanks & have a nice day.
**_Nowass_**

**Comment by Nowass** [comment]
One comment, just to get clear understanding ... my goal is to use **em** units. The **pt** I just use for such "workaround" ...

**Comment by mogest** [comment]
1em is 16pt by default, and 1px = 1pt in PDF land.  In your test files, you have a class applied to the top level <svg> element that sets the font size to 12pt, in both files.  In theory, this means using 0.75em inside that tag will get you 9pt text, because `em` is relative.  But looking at the files you've attached above, Chrome is rendering the 12pt and 1em text at totally different sizes, the same way prawn-svg does.

So I'm not really sure what's going on.

**Comment by Nowass** [comment]
well .... now I am a bit lost and confused ... let's forget the pt amd any other units and focus just on the **em** ...
The file with **em** units I export from Visio. When I take this file without any manual modification and display in Visio, Inkscape, Chrome and generated PDF, I'll get two different outputs ... the same I'll get from  Visio, Inkscape & Chrome and the other one is from generated PDF ... so from my point of view there is something wrong ...

[svgFontSize.pdf](https://github.com/mogest/prawn-svg/files/665900/svgFontSize.pdf)

**Comment by mogest** [comment]
Ahhh.  Now I understand, and fortunately it was not too difficult to track down the bug.  Please update from git master and let me know!

**Comment by Nowass** [comment]
WOW ... now it works like a charm ... GREAT! :-)

Many thanks for your support!

Merry Xmas
**_Nowass_**
