### ISSUE TITLE
add xlink:href support

### ISSUE THREAD

**Issue by nekolus** [mogest/prawn-svg#89]
When I try to embed png using image tag. I was getting this error. 
`block in pull_event': Undefined prefix xlink found (REXML::UndefinedNamespaceException)

Code that I tried.
Prawn::Document.generate("test.pdf") do
  svg "<svg><image width='115' height='30' xlink:href='https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/Wikipedia-logo.png/44px-Wikipedia-logo.png' /></svg>"
end

**Comment by mogest** [comment]
Hi @nekolus, looks like you closed the issue.  What was the resolution?  Also unfortunately your SVG got swallowed up so I can't see what your problem was.
