### ISSUE TITLE
issue with dotted line and SVG output in asciidoctor-pdf

### ISSUE THREAD

**Issue by ssydorov** [mogest/prawn-svg#91]
Hi All,
I got next error when I generate SVG diagramm with asciidoctor-pdf and asciidoctor-diagramm 
dotted lines looks ok with PNG output
![diagramm-png](https://cloud.githubusercontent.com/assets/24498236/22590878/27be079e-ea1a-11e6-8fb8-4d0819661350.png)
but not ok with SVG output
![diagramm-svg](https://cloud.githubusercontent.com/assets/24498236/22590879/2a34424a-ea1a-11e6-86f5-f7bcc4bacae3.png)
thanks.
Sergiy

**Comment by mojavelinux** [comment]
Can you please attach the SVG file?

**Comment by ssydorov** [comment]
Hi!
We don’t support that file type.  :(
but in any case... SVG file looks ok, but PDF is not ok

**Comment by ssydorov** [comment]
[4Dan.pdf](https://github.com/mogest/prawn-svg/files/751535/4Dan.pdf)

**Comment by ssydorov** [comment]
[4dan.txt](https://github.com/mogest/prawn-svg/files/751536/4dan.txt)

**Comment by ssydorov** [comment]
rename SVG to TXT (I could not attach SVG, ZIP)

**Comment by mojavelinux** [comment]
Remember, an SVG is just text, so you can just put it in a code block.

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" contentScriptType="application/ecmascript" contentStyleType="text/css" height="220px" preserveAspectRatio="none" style="width:272px;height:220px;" version="1.1" viewBox="0 0 272 220" width="272px" zoomAndPan="magnify"><defs><filter height="300%" id="fxfwkj4" width="300%" x="-1" y="-1"><feGaussianBlur result="blurOut" stdDeviation="2.0"/><feColorMatrix in="blurOut" result="blurOut2" type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 .4 0"/><feOffset dx="4.0" dy="4.0" in="blurOut2" result="blurOut3"/><feBlend in="SourceGraphic" in2="blurOut3" mode="normal"/></filter></defs><g><line style="stroke: #A80036; stroke-width: 1.0; stroke-dasharray: 5.0,5.0;" x1="32" x2="32" y1="39.6094" y2="181.0156"/><line style="stroke: #A80036; stroke-width: 1.0; stroke-dasharray: 5.0,5.0;" x1="245.5" x2="245.5" y1="39.6094" y2="181.0156"/><rect fill="#FEFECE" filter="url(#fxfwkj4)" height="31.6094" style="stroke: #A80036; stroke-width: 1.5;" width="44" x="8" y="3"/><text fill="#000000" font-family="sans-serif" font-size="14" lengthAdjust="spacingAndGlyphs" textLength="30" x="15" y="24.5332">Alice</text><rect fill="#FEFECE" filter="url(#fxfwkj4)" height="31.6094" style="stroke: #A80036; stroke-width: 1.5;" width="44" x="8" y="180.0156"/><text fill="#000000" font-family="sans-serif" font-size="14" lengthAdjust="spacingAndGlyphs" textLength="30" x="15" y="201.5488">Alice</text><rect fill="#FEFECE" filter="url(#fxfwkj4)" height="31.6094" style="stroke: #A80036; stroke-width: 1.5;" width="39" x="224.5" y="3"/><text fill="#000000" font-family="sans-serif" font-size="14" lengthAdjust="spacingAndGlyphs" textLength="25" x="231.5" y="24.5332">Bob</text><rect fill="#FEFECE" filter="url(#fxfwkj4)" height="31.6094" style="stroke: #A80036; stroke-width: 1.5;" width="39" x="224.5" y="180.0156"/><text fill="#000000" font-family="sans-serif" font-size="14" lengthAdjust="spacingAndGlyphs" textLength="25" x="231.5" y="201.5488">Bob</text><polygon fill="#A80036" points="234,67.6094,244,71.6094,234,75.6094,238,71.6094" style="stroke: #A80036; stroke-width: 1.0;"/><line style="stroke: #A80036; stroke-width: 1.0;" x1="32" x2="240" y1="71.6094" y2="71.6094"/><text fill="#000000" font-family="sans-serif" font-size="13" lengthAdjust="spacingAndGlyphs" textLength="135" x="39" y="67.1045">Authentication Request</text><polygon fill="#A80036" points="43,97.9609,33,101.9609,43,105.9609,39,101.9609" style="stroke: #A80036; stroke-width: 1.0;"/><line style="stroke: #A80036; stroke-width: 1.0; stroke-dasharray: 2.0,2.0;" x1="37" x2="245" y1="101.9609" y2="101.9609"/><text fill="#000000" font-family="sans-serif" font-size="13" lengthAdjust="spacingAndGlyphs" textLength="138" x="49" y="97.4561">Authentication Respone</text><polygon fill="#A80036" points="234,128.3125,244,132.3125,234,136.3125,238,132.3125" style="stroke: #A80036; stroke-width: 1.0;"/><line style="stroke: #A80036; stroke-width: 1.0;" x1="32" x2="240" y1="132.3125" y2="132.3125"/><text fill="#000000" font-family="sans-serif" font-size="13" lengthAdjust="spacingAndGlyphs" textLength="182" x="39" y="127.8076">Another authentication Request</text><polygon fill="#A80036" points="43,158.6641,33,162.6641,43,166.6641,39,162.6641" style="stroke: #A80036; stroke-width: 1.0;"/><line style="stroke: #A80036; stroke-width: 1.0; stroke-dasharray: 2.0,2.0;" x1="37" x2="245" y1="162.6641" y2="162.6641"/><text fill="#000000" font-family="sans-serif" font-size="13" lengthAdjust="spacingAndGlyphs" textLength="190" x="49" y="158.1592">another authentication Response</text></g></svg>
```

**Comment by mojavelinux** [comment]
I do not see these lines when I render this SVG using prawn-svg directly.

**Comment by mogest** [comment]
Me neither.
[lines.svg.pdf](https://github.com/mogest/prawn-svg/files/751779/lines.svg.pdf)

Are you sure you're running a recent version of prawn-svg?

**Comment by mojavelinux** [comment]
It appears so. My guess is this is either specific to Windows or it has to do with the encoding (though I can't reason as to why).

**Comment by mogest** [comment]
@ssydorov, do you have any further information you can give me to help me replicate your issue?

**Comment by ssydorov** [comment]
I don't know, what I can add....
source of my file
```
.The PlantUML Bob->Alice : hello
[plantuml, diagram-classes2, svg]
----
@startuml

Bob->Alice : hi
Bob<--Alice : bye
@enduml
----
```

command line

`>asciidoctor-pdf -r asciidoctor-diagram diagram.adoc`


SVG file is correct
`<?xml version="1.0" encoding="UTF-8" standalone="no"?><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" contentScriptType="application/ecmascript" contentStyleType="text/css" height="159px" preserveAspectRatio="none" style="width:114px;height:159px;" version="1.1" viewBox="0 0 114 159" width="114px" zoomAndPan="magnify"><defs><filter height="300%" id="f9qa3cl" width="300%" x="-1" y="-1"><feGaussianBlur result="blurOut" stdDeviation="2.0"/><feColorMatrix in="blurOut" result="blurOut2" type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 .4 0"/><feOffset dx="4.0" dy="4.0" in="blurOut2" result="blurOut3"/><feBlend in="SourceGraphic" in2="blurOut3" mode="normal"/></filter></defs><g><line style="stroke: #A80036; stroke-width: 1.0; stroke-dasharray: 5.0,5.0;" x1="29" x2="29" y1="39.6094" y2="120.3125"/><line style="stroke: #A80036; stroke-width: 1.0; stroke-dasharray: 5.0,5.0;" x1="85" x2="85" y1="39.6094" y2="120.3125"/><rect fill="#FEFECE" filter="url(#f9qa3cl)" height="31.6094" style="stroke: #A80036; stroke-width: 1.5;" width="39" x="8" y="3"/><text fill="#000000" font-family="sans-serif" font-size="14" lengthAdjust="spacingAndGlyphs" textLength="25" x="15" y="24.5332">Bob</text><rect fill="#FEFECE" filter="url(#f9qa3cl)" height="31.6094" style="stroke: #A80036; stroke-width: 1.5;" width="39" x="8" y="119.3125"/><text fill="#000000" font-family="sans-serif" font-size="14" lengthAdjust="spacingAndGlyphs" textLength="25" x="15" y="140.8457">Bob</text><rect fill="#FEFECE" filter="url(#f9qa3cl)" height="31.6094" style="stroke: #A80036; stroke-width: 1.5;" width="44" x="61" y="3"/><text fill="#000000" font-family="sans-serif" font-size="14" lengthAdjust="spacingAndGlyphs" textLength="30" x="68" y="24.5332">Alice</text><rect fill="#FEFECE" filter="url(#f9qa3cl)" height="31.6094" style="stroke: #A80036; stroke-width: 1.5;" width="44" x="61" y="119.3125"/><text fill="#000000" font-family="sans-serif" font-size="14" lengthAdjust="spacingAndGlyphs" textLength="30" x="68" y="140.8457">Alice</text><polygon fill="#A80036" points="73,67.6094,83,71.6094,73,75.6094,77,71.6094" style="stroke: #A80036; stroke-width: 1.0;"/><line style="stroke: #A80036; stroke-width: 1.0;" x1="29.5" x2="79" y1="71.6094" y2="71.6094"/><text fill="#000000" font-family="sans-serif" font-size="13" lengthAdjust="spacingAndGlyphs" textLength="10" x="36.5" y="67.1045">hi</text><polygon fill="#A80036" points="40.5,97.9609,30.5,101.9609,40.5,105.9609,36.5,101.9609" style="stroke: #A80036; stroke-width: 1.0;"/><line style="stroke: #A80036; stroke-width: 1.0; stroke-dasharray: 2.0,2.0;" x1="34.5" x2="84" y1="101.9609" y2="101.9609"/><text fill="#000000" font-family="sans-serif" font-size="13" lengthAdjust="spacingAndGlyphs" textLength="21" x="46.5" y="97.4561">bye</text></g></svg>`

but pdf file is not correct 
[diagram.pdf](https://github.com/mogest/prawn-svg/files/760330/diagram.pdf)

additional info:
`system is Win 10`

asciidoctor
```
>asciidoctor-pdf -v
Asciidoctor PDF 1.5.0.alpha.13 using Asciidoctor 1.5.5 [http://asciidoctor.org]
Runtime Environment (ruby 2.3.3p222 (2016-11-21 revision 56859) [x64-mingw32]) (lc:UTF-8 fs:Windows-1251 in:- ex:UTF-8)
```

**Comment by ssydorov** [comment]
from my side, problem is not with SVG creation. SVG is ok. problem in final PDF file, thanks!

**Comment by ssydorov** [comment]
gem prawn version 
```
prawn (2.1.0)
prawn-icon (1.3.0, 1.2.0)
prawn-svg (0.26.0, 0.25.2)
prawn-table (0.2.2)
prawn-templates (0.0.4, 0.0.3)
```

**Comment by mogest** [comment]
@ssydorov, I think you have a problem with your PDF viewer.  I loaded the PDF file that you supplied above using Chrome's PDF viewer on Windows 10 and this is what I see:

![svg](https://cloud.githubusercontent.com/assets/23133/22847066/9f097ea6-f04f-11e6-99d5-616cfd8eb7e2.png)

It looks identical to the SVG file (apart from the drop shadow under the boxes).  Try a different PDF viewer?

**Comment by ssydorov** [comment]
Hi,
yes, I checked in chrome now.... It looks ok in chrome... But in Adobe Acrobat X and in Adobe Acrobat DC is not ok.
How is right in this case?

**Comment by mogest** [comment]
Hmm I'd expect it to be right in Adobe Acrobat.  I'll look into this further, thanks for the update.

**Comment by mogest** [comment]
Thanks for your persistence @ssydorov.  Surprising that prawn-svg has been rendering lines wrong for the last 7 years, but there you go!  This should look better for you.

[lines.svg.pdf](https://github.com/mogest/prawn-svg/files/768068/lines.svg.pdf)

Thanks again for your help :+1:

**Comment by mojavelinux** [comment]
I can't believe I didn't think to check the viewer. Sure enough, Adobe Acrobat (even on Linux) is showing the lines @ssydorov was reporting. Wow. Nice investigative work @mogest! Amazing that Prawn has been doing it wrong all along.

Does there need to be a corresponding change in Prawn core?

**Comment by mogest** [comment]
I don't think so @mojavelinux.  PDF spec doesn't have a concept of a line in isolation, they're always as part of a path that may be two dimensional and therefore may be filled.  So a filled line seems to me to be valid PDF, even though how to render that seems to be under debate between PDF renderers.

I'd say it's valid that Prawn allows a filled line, but prawn-svg shouldn't because that concept doesn't exist in SVG land.  Would you agree?

**Comment by mojavelinux** [comment]
:+1: 

Thanks for the follow-up!

**Comment by ssydorov** [comment]
Thank you very much to all of you!

**Comment by mojavelinux** [comment]
@mogest Could you let me know what version you are going to use for the next release? I want to include that version in the version range when I release Asciidoctor PDF so that users will get the update when it comes.

**Comment by mogest** [comment]
It'll be 0.27.0.

**Comment by mojavelinux** [comment]
Great!
