### ISSUE TITLE
Big square aren't square

### ISSUE THREAD

**Issue by rempargo** [mogest/prawn-svg#92]
Modified the first sample, but the red rectangle is not square, even width and height are equal.

```
require 'prawn-svg'

Prawn::Document.generate("test.pdf") do
  svg '<svg><rect width="100" height="100" fill="blue"></rect></svg>', at: [100,100]
  svg '<svg><rect width="200" height="200" fill="red"></rect></svg>', at: [100,400]
end
```

**Comment by mogest** [comment]
Thanks for your report, @rempargo.  prawn-svg isn't handling svg elements with no width or height properly.  A workaround is to put in a width and height attribute on the svg element.  I'll get on to a fix this weekend.

**Comment by mojavelinux** [comment]
While the fix for this issue solved the problem of an SVG with no viewBox and no explicit dimensions, it broke the case of an SVG with a viewBox and no explicit dimensions.
