### ISSUE TITLE
fallback_font_name or supplying additional fonts?

### ISSUE THREAD

**Issue by LuckDragon82** [mogest/prawn-svg#95]
I would like to supply additional fonts so I can process emoji and Kanji (and possibly other things). I can't seem to get the svg processor to pick up the new font.

```
  def process_canvases(canvases)
    Prawn::SVG::FontRegistry.font_path << File.join(Rails.root, "app/assets/fonts")
    canvases.each_with_index do |canvas, index|
      pdf.svg canvas['project'], fallback_font_name: 'emoji' # also tried passing DejaVuSans...
      pdf.start_new_page unless canvases.length == index + 1
    end
  end

  def setup_fonts
    pdf.font_families.update('kanji' => { normal: 'app/assets/fonts/gkai00mp.ttf' })
    pdf.font_families.update('emoji' => { normal: 'app/assets/fonts/DejaVuSans.ttf', bold: 'app/assets/fonts/DejaVuSans-Bold.ttf' })
  end
```

Any idea what I'm doing wrong? What is the correct way to pass new fonts in? Is there any way to supply more than 1 fallback font? Thank you.

-Joshua

**Comment by mogest** [comment]
Hi Joshua, thanks for the report.

Are you sure that it's using the fallback font?  Have you tried explicitly specifying the font in the SVG, and does that work?

**Comment by mogest** [comment]
Oh, also take the path out of the `setup_fonts` method, you've already specified the font path above.  It should just be `gkai00mp.ttf`.

**Comment by LuckDragon82** [comment]
Boom. I used nokogiri to cycle through the text elements and add the appropriate font-family and it works perfectly. Thank you.

**Comment by brandoncc** [comment]
@LuckDragon82 would it be possible to get a snippet of code that shows what you did with nokogiri? I need to do the same thing and I'm not sure exactly what you did.

Thanks!

**Comment by brandoncc** [comment]
@mogest I have tried the same thing, and I can confirm that it isn't trying to use my fallback font.

```ruby
svg collage_text.svg_markup, at: [left, top], width: width, fallback_font: 'DejaVuSans'
```

This throws an error when it hits an emoji, but if I set the font family in the SVG it doesn't. Why isn't the fallback working? Also, Prawn supports an array of fallback fonts. Is there a reason prawn-svg doesn't?

**Comment by brandoncc** [comment]
I figured out just after submitting my question that I needed to use `fallback_font_name` instead of `fallback_font`. That fixed my issue. The fallback is being used now.

I would still like to provide an array though, to support more characters. Is that possible?

**Comment by mogest** [comment]
As far as I can tell, Prawn only takes one font.  The fallback font is used by prawn-svg if the CSS- or attribute-specified font isn't found on the system, but it doesn't do anything as fancy as falling back if a specific character isn't found inside the given font sorry.

**Comment by mojavelinux** [comment]
That's not the case. Prawn does analyze each fallback font until it finds a font that provides the glyph. Prawn's own docs confirm this:

> Prawn enables the declaration of fallback fonts for those glyphs that may not be present in the desired font. Use the fallback_fonts option with any of the text or text box methods, or set fallback_fonts document-wide.

Here's where the logic for this feature can be found:

https://github.com/prawnpdf/prawn/blob/master/lib/prawn/text/formatted/box.rb#L417-L475

**Comment by mogest** [comment]
Ah interesting. I'm on my phone now so can't check, but is this just in Box
(which can't be used with prawn-svg) or available to the text primaries
too? If the latter it shouldn't be too hard to wire up. The prawn-svg
fallback font is unrelated to the prawn fallback system which I did not
know existed :)

**Comment by brandoncc** [comment]
As far as I know, fallbacks work with all text in Prawn. We have an array
of about 8 fallback fonts for different spoken languages. It would be very
much appreciated if per glyph fallbacks worked with multiple fonts! I was
actually surprised you didn't use the same fallbacks as the rest of the
document, but that makes sense now.

**Comment by mogest** [comment]
Neat. Would I be able to ask that you share a simple SVG that illustrates
this functionality? It'd make implementation faster!

**Comment by brandoncc** [comment]
Hi @mogest, I missed your request sorry!

If I understand what you are asking, you want to see how prawn allows me to set my fallback fonts. If you go to [the manual](https://prawnpdf.org/manual.pdf) and search "fallback_fonts" you will see the section about it where it shows setting them on a `#text` element.

As noted at the end of that section, you can also set them document-wide. This is done by defining a `#fallback_fonts` method on the document. This is what ours looks like:

```ruby
  def fallback_fonts
    [
      'IPAGothic',
      'IPAMincho',
      'IPAPMincho',
      'IPAPGothic',
      'WenQuanYi Zen Hei',
      'DejaVuSans',
      'DroidSans',
      'DroidSerif'
    ]
  end
```

The only elements in our document which do not automatically use these fonts as fallbacks (on a per-character basis) are `#svg` elements.

I hope this helps, please let me know if you need anything else.

**Comment by mogest** [comment]
Thanks Brandon. Could you give me a tiny SVG file that would trigger the
use of fallback fonts please? I'm not used to the idea, so I'm not sure how
I'd go about testing that it's working at the moment :) If I had an SVG to
put in our test suite then I could confidently implement it I think.

**Comment by brandoncc** [comment]
This should work:

```svg
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="257px" height="193px" viewBox="0 0 257 193" version="1.1">
  <g>
    <text font-family="Times-Roman">
      <tspan x="47" y="68"> hello ƒ 你好再见 ƒ goodbye </tspan>
    </text>
    <text font-family="Times-Roman">
      <tspan x="121" y="112">😄</tspan>
    </text>
  </g>
</svg>
```

I'm not sure about the namespacing, so feel free to adjust that as needed for prawn-svg. The text content just needs to be characters that are not in the `Times-Roman` font family. I used the text from the example in the prawn manual, except I also added the emoji as another test.

**Comment by brandoncc** [comment]
I'm just checking in to see if this was helpful. Was it @mogest? Thanks for any time you are spending on this, it is very appreciated!

**Comment by mogest** [comment]
Yes, thanks Brandon!  I have been flooded with work and family stuff but
I'm hoping to get to this in the weekend.

**Comment by brandoncc** [comment]
That sounds great. If there is anything else I can do to help, please let me know.

**Comment by mogest** [comment]
Thanks for your patience, I've spent a bit of time on it just now.

Not good news I'm sorry, only the Box text functions support fallback fonts.  I can't remember why but when I was last working with the text implementation I found I couldn't use Box.  The code also uses `width_of` to determine how long the text will be, and this too only works with one font.

I'm sure it's possible to implement it, but it'd be a big piece of work.  It'd have to manually split the string and find which fonts support which glyphs and then stitch them together (that's what Box does, see [this code for an example](https://github.com/prawnpdf/prawn/blob/3658d5125c3b20eb11484c3b039ca6b89dc7d1b7/lib/prawn/text/formatted/box.rb#L417-L475)), and also keep track of the cumulative width.  prawn-svg is 11 years old and this is the first time it's come up so it doesn't seem like a thing that's holding the community back from benefiting from it.  Sorry :(

**Comment by brandoncc** [comment]
That's a huge bummer for us, but I respect your decision. Thank you for the time you invested in researching this.

**Comment by brandoncc** [comment]
By the way, the first time it came up was actually in 2017 when this issue was opened. Somehow that user came up with a hack to cycle through elements using nokogiri since prawn-svg didn't support it. I sure wish I knew how they achieved that.

Again, thanks for the help and I hope this does eventually change....although we may be forced to find a different solution by then.

**Comment by mogest** [comment]
I'm happy to help with the workaround the other person posted above, I'm
pretty sure I understand the approach they took. It sounds like they load
the SVG in and parse with nokogiri (REXML works too, that's what prawn-svg
uses), then they go find all the text elements, and if the text elements
has text that needs a different font they set the font family property on
that element. Then render it back to a string and pass it to prawn-svg.
Happy to go over specifics if you'd like.

**Comment by brandoncc** [comment]
Thanks for that. I have the same understanding as you described, but I'm not sure how that would work on a character-by-character basis. For example, what if the text is Korean and has emoji? This would use the Korean font as a fallback, but also use an emoji font as a second fallback. Do I have a misunderstanding of how it would work?

**Comment by mogest** [comment]
Hmm I wonder if you could replace any emoji with a tspan that has the
different font on it?

I'm not sure about the breadth of your use case to make a good suggestion,
but assuming a bunch of things, how about:
* Go through every text and tspan element, looking at text content
* Detect which fonts are required for the glpyhs
* If it's all the same font, just set the font family on that element
* If there are multiple fonts, replace the text content with a series of
tspans, one for each group of glyphs that belong to the same font

I mean that sounds like a lot of hassle. :( But should work assuming you
know which glyphs are currently not rendering correctly.

**Comment by brandoncc** [comment]
I currently don't have any idea how to tell what fonts are not rendering properly or how to find the fonts which will render them correctly. I wonder if I could leverage the Prawn API to tell me these things?
