### ISSUE TITLE
Svg's not showing properly

### ISSUE THREAD

**Issue by jonathan0211** [mogest/prawn-svg#97]
I am using prawn-svg to append charts from highcharts library, but They are not being properly displayed, I am using CombinePDF to. This is the file generated
[fb6d1a9c-7a4a-4784-bcee-15d6fda8b335.pdf](https://github.com/mogest/prawn-svg/files/1350128/fb6d1a9c-7a4a-4784-bcee-15d6fda8b335.pdf), on Chrome pdf viewer the file is showed properly, but on my ubuntu pdf viewer something went wrong. This is the proper result 
![a](https://user-images.githubusercontent.com/7417383/31095973-fd517fd8-a790-11e7-9dcc-cd98c84da7b8.png).

**Comment by mogest** [comment]
Hi @jonathan0211. Sorry, I need a lot more information to diagnose what's going wrong.

Can you give me at minimum a small SVG file that renders properly in a web browser and does not render correctly with prawn-svg?  Better still, you should experiment to see what are the features/tags that prawn-svg is not rendering correctly.

**Comment by mogest** [comment]
Closing due to insufficient information and no response.
