### ISSUE TITLE
fillrule="evenodd" not supported

### ISSUE THREAD

**Issue by kalvdans** [mogest/prawn-svg#99]
I have a pictogram which is not rendered properly by prawn-svg. It is due to a <path> element containing two closed subpaths where the second subpath should carve out a hole in the first subpath. I attach here:

* the svg file as txt (should be a radioactive symbol)
[warning-radioactive.svg.txt](https://github.com/mogest/prawn-svg/files/1458523/warning-radioactive.svg.txt)

* the rendered pdf (displays a black triangle)
[test.pdf](https://github.com/mogest/prawn-svg/files/1458526/test.pdf)

* the test script
[testfile.rb.txt](https://github.com/mogest/prawn-svg/files/1458530/testfile.rb.txt)

**Comment by mogest** [comment]
Thanks @kalvdans.  Do you mind if I put the SVG above into the SVG test suite, licensed under MIT?

**Comment by kalvdans** [comment]
The source of the pictogram is public domain, as far as I can trace from GallerySignauxDangers.2.1.0.oxt where I took it from. So you can place it in the test suite under MIT.

**Comment by mogest** [comment]
Nice one. I used the logic from your pull request and took the opportunity to rewrite the surrounding code a bit, and add some tests. Thanks so much for the idea and implementation!

I'll release a new gem in the next couple of weeks.
